### ISSUE TITLE
got the same error...

### ISSUE THREAD

**Issue by maheshvarma27** [Redocly/redoc#1091]
got the same error...
TypeError [ERR_INVALID_URL]: Invalid URL: undefined
    at onParseError (internal/url.js:241:17)
    at new URL (internal/url.js:319:5)
    at _.chain.map (C:\Users\MAHESH\work\nodeWithReact\routes\surveyRoutes.js:30:34)
    at arrayMap (C:\Users\MAHESH\work\nodeWithReact\node_modules\lodash\lodash.js:639:23)
    at Function.map (C:\Users\MAHESH\work\nodeWithReact\node_modules\lodash\lodash.js:9554:14)
    at interceptor (C:\Users\MAHESH\work\nodeWithReact\node_modules\lodash\lodash.js:16997:35)
    at thru (C:\Users\MAHESH\work\nodeWithReact\node_modules\lodash\lodash.js:8795:14)
    at C:\Users\MAHESH\work\nodeWithReact\node_modules\lodash\lodash.js:4368:28
    at arrayReduce (C:\Users\MAHESH\work\nodeWithReact\node_modules\lodash\lodash.js:683:21)
    at baseWrapperValue (C:\Users\MAHESH\work\nodeWithReact\node_modules\lodash\lodash.js:4367:14)
    at LazyWrapper.lazyValue [as value] (C:\Users\MAHESH\work\nodeWithReact\node_modules\lodash\lodash.js:1859:16)
    at baseWrapperValue (C:\Users\MAHESH\work\nodeWithReact\node_modules\lodash\lodash.js:4365:25)
    at LodashWrapper.wrapperValue (C:\Users\MAHESH\work\nodeWithReact\node_modules\lodash\lodash.js:9050:14)
    at app.post (C:\Users\MAHESH\work\nodeWithReact\routes\surveyRoutes.js:52:12)
    at Layer.handle [as handle_request] (C:\Users\MAHESH\work\nodeWithReact\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\MAHESH\work\nodeWithReact\node_modules\express\lib\router\route.js:137:13)

**Comment by lornajane** [comment]
This old issue doesn't have enough context for me to replicate the problem. I'm closing it, but please let us know if you are still running into problems when using the newest versions of Redoc.
