### ISSUE TITLE
Expected a file path, URL, or object. Got undefined

### ISSUE THREAD

**Issue by ZeroWM** [Redocly/redoc#1115]
Something went wrong...
Expected a file path, URL, or object. Got undefined
Stack trace
Error: Expected a file path, URL, or object. Got undefined
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:49:5301
    at f.parse (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:61:69701)
    at f.resolve (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:61:70566)
    at f.bundle (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:61:70926)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:101:29584
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:22:2545
    at Object.next (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:22:2650)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:22:1587
    at new Promise (<anonymous>)
    at u (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:22:1361)

ReDoc Version: 2.0.0-rc.18
Commit: cd9fd618

when i used npm run start redoc, it tells me the error message, can you tell me why? how can i solve this problem?

**Comment by lornajane** [comment]
Due to the age of this issue, I'm closing it, but please do open a new issue if you see this problem again!
