### ISSUE TITLE
Module not found error with latest version

### ISSUE THREAD

**Issue by sanderson** [Redocly/redoc#1122]
Just updated to the 0.9.2 version of redoc-cli from the NPM registry. I get the following error when trying to generate the HTML:

```
Error: No valid exports main found for '/usr/local/lib/node_modules/redoc-cli/node_modules/merge-anything'
    at resolveExportsTarget (internal/modules/cjs/loader.js:611:9)
    at applyExports (internal/modules/cjs/loader.js:492:14)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:643:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:941:27)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/redoc-cli/node_modules/styled-components/dist/styled-components.cjs.js:17:29)
    at Module._compile (internal/modules/cjs/loader.js:1121:30) {
  code: 'MODULE_NOT_FOUND'
}
```

**Comment by sanderson** [comment]
Doing some testing, this appears to be an issue with Node 13.2.0.

**Comment by shaneHowearth** [comment]
Not sure if this is related, I'm trying to use redoc-cli and getting
redoc-cli --version
0.9.2
node --version
v12.13.1

```
(node:15526) Warning: require() of ES modules is not supported.
require() of /usr/lib/node_modules/redoc-cli/node_modules/merge-anything/dist/index.cjs.js from /usr/lib/node_modules/redoc-cli/node_modules/styled-components/dist/styled-components.cjs.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.cjs.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /usr/lib/node_modules/redoc-cli/node_modules/merge-anything/package.json.
Prerendering docs
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at new MediaContentModel (/usr/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:9351:34)
    at new RequestBodyModel (/usr/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:9400:28)
    at OperationModel.get (/usr/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:9515:54)
    at OperationModel.get [as requestBody] (/usr/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:8179:42)
    at Object.children (/usr/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:12880:125)
    at ReactDOMServerRenderer.render (/usr/lib/node_modules/redoc-cli/node_modules/react-dom/cjs/react-dom-server.node.development.js:3855:55)
    at ReactDOMServerRenderer.read (/usr/lib/node_modules/redoc-cli/node_modules/react-dom/cjs/react-dom-server.node.development.js:3536:29)
    at Object.renderToString (/usr/lib/node_modules/redoc-cli/node_modules/react-dom/cjs/react-dom-server.node.development.js:4245:27)
    at /usr/lib/node_modules/redoc-cli/index.js:211:29
```

**Comment by shaneHowearth** [comment]
I get this error too (I was using an out of date node for the previous report)
```Error: No valid exports main found for '/usr/lib/node_modules/redoc-cli/node_modules/merge-anything'
    at resolveExportsTarget (internal/modules/cjs/loader.js:611:9)
    at applyExports (internal/modules/cjs/loader.js:492:14)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:643:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:941:27)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (/usr/lib/node_modules/redoc-cli/node_modules/styled-components/dist/styled-components.cjs.js:17:29)
    at Module._compile (internal/modules/cjs/loader.js:1121:30) {
  code: 'MODULE_NOT_FOUND'
}
```

**Comment by futureinvasion** [comment]
Got this error too.

**Comment by RomanHotsiy** [comment]
Looks like some styled-components issue: https://github.com/styled-components/styled-components/issues/2907

Can't do anything about that yet.

**Comment by lornajane** [comment]
Closing this since `redoc-cli` is deprecated so hopefully this is no longer causing anyone a problem! Users should [migrate to Redocly CLI](https://redocly.com/docs/cli/guides/migrate-from-redoc-cli/).
