### ISSUE TITLE
Lack of support of global responses

### ISSUE THREAD

**Issue by Tsingh315** [Redocly/redoc#1213]
My openapi.yml has global responses

## yaml openapi
```yaml
... 
components:
  responses:
    some:
      description: Description of some_
```

This is rendered fine in swagger editor. But in redoc I get following error
```
## Error
Something went wrong...
Cannot read property 'description' of undefined
```

```
**Stack trace**
TypeError: Cannot read property 'description' of undefined
    at Function.e.buildStructure (https://cdn.jsdelivr.net/npm/redoc@2.0.0-alpha.17/bundles/redoc.standalone.js:104:100109)
    at e.get (https://cdn.jsdelivr.net/npm/redoc@2.0.0-alpha.17/bundles/redoc.standalone.js:104:88187)
    at Lt (https://cdn.jsdelivr.net/npm/redoc@2.0.0-alpha.17/bundles/redoc.standalone.js:22:36958)
    at e.computeValue (https://cdn.jsdelivr.net/npm/redoc@2.0.0-alpha.17/bundles/redoc.standalone.js:22:8397)
    at e.trackAndCompute (https://cdn.jsdelivr.net/npm/redoc@2.0.0-alpha.17/bundles/redoc.standalone.js:22:8245)
    at e.get (https://cdn.jsdelivr.net/npm/redoc@2.0.0-alpha.17/bundles/redoc.standalone.js:22:7287)
    at e.read (https://cdn.jsdelivr.net/npm/redoc@2.0.0-alpha.17/bundles/redoc.standalone.js:22:12294)
    at e.get (https://cdn.jsdelivr.net/npm/redoc@2.0.0-alpha.17/bundles/redoc.standalone.js:22:14617)
    at e.get (https://cdn.jsdelivr.net/npm/redoc@2.0.0-alpha.17/bundles/redoc.standalone.js:104:102755)
    at e.computeValue (https://cdn.jsdelivr.net/npm/redoc@2.0.0-alpha.17/bundles/redoc.standalone.js:22:8534)

ReDoc Version: 2.0.0-alpha.17
Commit: de177a0
```

**Comment by RomanHotsiy** [comment]
This has nothing to do with global responses. Can you send the whole minimal reproducible specification so I can reproduce it? Most likely your definition is invalid.

**Comment by ahmadnassri** [comment]
I had the same issue, solved by adding "info" top-level object in the spec file even if it's empty
