### ISSUE TITLE
TypeError: e.name.localCompare with 2.0.0-rc.25

### ISSUE THREAD

**Issue by donbowman** [Redocly/redoc#1218]
I think yesterday a new version was pushed to CDN, its broke on rendering with the below stack trace (and the below input).

```
TypeError: e.name.localCompare is not a function
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:130:56091
    at Array.sort (<anonymous>)
    at e.initDiscriminator (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:130:56004)
    at e.init (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:130:54621)
    at new e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:130:50979)
    at e.init (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:130:54084)
    at new e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:130:50979)
    at new e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:130:58730)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:130:60086
    at Array.map (<anonymous>)

ReDoc Version: 2.0.0-rc.25
Commit: 89054da
```

with input
```
<!DOCTYPE html>
<html>
  <head>
    <title>Agilicus API</title>
    <!-- needed for adaptive design -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">

    <style>
      body {
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <redoc spec-url='https://storage.googleapis.com/agilicus/api/agilicus-openapi.yaml'></redoc>
    <script src="https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js"> </script>
  </body>
</html>

```

**Comment by RomanHotsiy** [comment]
Pinpoint to `2.0.0-rc.25` for now while new version is coming.
Thanks for the report.

**Comment by RomanHotsiy** [comment]
Should be fixed in rc.26
