### ISSUE TITLE
"Document must be valid OpenAPI 3.0.0 definition" for schema which is valid according to openapi-cli

### ISSUE THREAD

**Issue by Ark-kun** [Redocly/redoc#1252]
https://redocly.github.io/redoc/?nocors&url=https://raw.githubusercontent.com/Ark-kun/pipelines/8a08173d7f4072c3baf45bf9492a7a736154ac00/sdk/python/kfp/components/structures/components.json_schema.json

```
Something went wrong...
Document must be valid OpenAPI 3.0.0 definition
Stack trace
Error: Document must be valid OpenAPI 3.0.0 definition
    at e.validate (https://redocly.github.io/redoc/redoc-demo.bundle.js:1:42666)
    at new e (https://redocly.github.io/redoc/redoc-demo.bundle.js:1:42441)
    at new Mt (https://redocly.github.io/redoc/redoc-demo.bundle.js:1:46254)
    at new e (https://redocly.github.io/redoc/redoc-demo.bundle.js:7:60321)
    at t.makeStore (https://redocly.github.io/redoc/redoc-demo.bundle.js:1:75851)
    at t.render (https://redocly.github.io/redoc/redoc-demo.bundle.js:1:76799)
    at Fs (https://redocly.github.io/redoc/redoc-demo.bundle.js:83:70004)
    at Ds (https://redocly.github.io/redoc/redoc-demo.bundle.js:83:69799)
    at ga (https://redocly.github.io/redoc/redoc-demo.bundle.js:83:105543)
    at cl (https://redocly.github.io/redoc/redoc-demo.bundle.js:83:96792)

ReDoc Version: 2.0.0-rc.28
Commit: 18dbd62
```

```
$ npx @redocly/openapi-cli validate https://raw.githubusercontent.com/Ark-kun/pipelines/8a08173d7f4072c3baf45bf9492a7a736154ac00/sdk/python/kfp/components/structures/components.json_schema.json
npx: installed 73 in 5.851s
Will validate from URL
https://raw.githubusercontent.com/Ark-kun/pipelines/8a08173d7f4072c3baf45bf9492a7a736154ac00/sdk/python/kfp/components/structures/components.json_schema.json results. Errors: 0, warnings: 0
```

**Comment by RomanHotsiy** [comment]
It's an issue in `openapi-cli`, you have a syntax error in your definition:

![image](https://user-images.githubusercontent.com/3975738/81038680-8fba6580-8eaf-11ea-9d8e-ef6fa269e13f.png)
