### ISSUE TITLE
t.map is not a function (version 2.0.0-rc.28)

### ISSUE THREAD

**Issue by duncte123** [Redocly/redoc#1255]
the documentation that caused this error is https://pastebin.com/5d5MDDBz
Redoc configuration can be found [here](https://github.com/duncte123/docs.duncte123.com/blob/master/index.html)

Update: this seems to be caused by `enum="[NORMAL, TAG, ONE_GUILD, ALL_GUILD]",` on a property

Exception:
```
Something went wrong...
t.map is not a function
Stack trace
TypeError: t.map is not a function
    at t.render (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:136:46816)
    at Fa (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:106:69906)
    at Da (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:106:69701)
    at gs (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:106:105445)
    at cl (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:106:96694)
    at sl (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:106:96619)
    at Js (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:106:93700)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:106:45362
    at t.unstable_runWithPriority (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:114:3844)
    at qo (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:106:45071)

ReDoc Version: 2.0.0-rc.28
Commit: 18dbd62
```

**Comment by RomanHotsiy** [comment]
enum must be an array, not a string: `enum=["normal", "tag" ...]`

**Comment by osamaramihafez** [comment]
Is there any other reason we might encounter this error? All of my enums are formatted correctly
