### ISSUE TITLE
stack trace in later versions of 2.0rc

### ISSUE THREAD

**Issue by jnardone** [Redocly/redoc#1340]
Starting in 2.0.0-rc32 or rc33 our generated documentation (which comes out of `joi-to-swagger`) the content no longer renders.

It simply shows
```
TypeError: Cannot read property 'style' of undefined
    at new e (https://mysite.io/static/redoc/redoc.standalone.js:2:742095)
    at https://mysite.io/static/redoc/redoc.standalone.js:2:749211
    at Array.map (<anonymous>)
    at e.get (https://mysite.io/static/redoc/redoc.standalone.js:2:749187)
    at e.get (https://mysite.io/static/redoc/redoc.standalone.js:2:723358)
    at https://mysite.io/static/redoc/redoc.standalone.js:2:911527
    at hs (https://mysite.io/static/redoc/redoc.standalone.js:2:498576)
    at sl (https://mysite.io/static/redoc/redoc.standalone.js:2:487712)
    at il (https://mysite.io/static/redoc/redoc.standalone.js:2:487637)
    at Ks (https://mysite.io/static/redoc/redoc.standalone.js:2:484667)
```

Is this a known problem?  How would I troubleshoot this?  The stack trace with the minified assets that we serve this with are not easy to dig through.  Is there documentation on how to investigate the problem?

**Comment by KillerCodeMonkey** [comment]
same issue here. Setting the redoc-cli version to `0.9.8` fixed the issue for us.

**Comment by pkat** [comment]
I'm seeing the same error on versions between `2.0.0-rc.33` to `2.0.0-rc.36`.

`2.0.0-rc.31` works fine and does not show the error.

**Comment by jnardone** [comment]
I can confirm this broke after rc32 for us.

**Comment by adamaltman** [comment]
Can you provide us with any reproduction? (Are you able to share an OpenAPI definition that reproduces the error?)

**Comment by jnardone** [comment]
Here's a copy of our .json file which works with .32 and not later.  

[1340.json.zip](https://github.com/Redocly/redoc/files/5062541/1340.json.zip)

**Comment by RomanHotsiy** [comment]
You openapi definition is invalid. Parameter `in` can't have value "route". It should be "path". I added a fallback so redoc doesn't crash.

You can use [openapi-cli](https://github.com/Redocly/openapi-cli) to validate your definition before passing it to redoc.

**Comment by jnardone** [comment]
I’ll try to find the bug in the set of components we use to generate our help. Thanks.
