### ISSUE TITLE
Cannot find module 'react'

### ISSUE THREAD

**Issue by DSigmund** [Redocly/redoc#1349]
Ive got a little problem, maybe someone can help?

**redoc-cli@0.9.10**
**redoc@2.0.0-rc.36**
(both globally)

`redoc-cli bundle openapi.yaml`

```
internal/modules/cjs/loader.js:1033
  throw err;
  ^

Error: Cannot find module 'react'
Require stack:
- /usr/local/lib/node_modules/redoc/bundles/redoc.lib.js
- /usr/local/lib/node_modules/redoc-cli/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1030:15)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/redoc/bundles/redoc.lib.js:107:18)
    at __webpack_require__ (/usr/local/lib/node_modules/redoc/bundles/redoc.lib.js:36:30)
    at Module.<anonymous> (/usr/local/lib/node_modules/redoc/bundles/redoc.lib.js:6861:23)
    at __webpack_require__ (/usr/local/lib/node_modules/redoc/bundles/redoc.lib.js:36:30)
    at /usr/local/lib/node_modules/redoc/bundles/redoc.lib.js:100:18
    at /usr/local/lib/node_modules/redoc/bundles/redoc.lib.js:103:10 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/redoc/bundles/redoc.lib.js',
    '/usr/local/lib/node_modules/redoc-cli/index.js'
  ]
}
```

**Comment by RomanHotsiy** [comment]
You should install react separately. It is marked as `peerDependency`

**Comment by RomanHotsiy** [comment]
Oh. I'm sorry. I didn't notice you use redoc-cli.

Can you remove redoc package globally? It is not required to install it globally.

**Comment by DSigmund** [comment]
Hi, Thank you.
i removed the redoc-package from global, same error...

**Comment by RomanHotsiy** [comment]
Could you reinstall redoc-cli. Do you have same error when using npx?

**Comment by DSigmund** [comment]
Well, a reinstall on global did the trick. Thank you!
