### ISSUE TITLE
Passing JSON object to spec results in error

### ISSUE THREAD

**Issue by pratikthanki** [Redocly/redoc#1460]
Hi - when looking to use `RedocStandalone` and passing a json object to `spec`. I am using the spec from: http://petstore.swagger.io/v2/swagger.json

I get the following error:

```
Document must be valid OpenAPI 3.0.0 definition
Stack trace
Error: Document must be valid OpenAPI 3.0.0 definition
    at OpenAPIParser.validate (http://localhost:3000/static/js/0.chunk.js:101908:19)
    at new OpenAPIParser (http://localhost:3000/static/js/0.chunk.js:101895:16)
    at new SpecStore (http://localhost:3000/static/js/0.chunk.js:102219:25)
    at new AppStore (http://localhost:3000/static/js/0.chunk.js:105287:23)
    at StoreBuilder.makeStore (http://localhost:3000/static/js/0.chunk.js:103097:20)
    at StoreBuilder.render (http://localhost:3000/static/js/0.chunk.js:103183:25)
    at finishClassComponent (http://localhost:3000/static/js/0.chunk.js:71760:35)
    at updateClassComponent (http://localhost:3000/static/js/0.chunk.js:71713:28)
    at beginWork (http://localhost:3000/static/js/0.chunk.js:73298:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/0.chunk.js:58263:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/0.chunk.js:58312:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/0.chunk.js:58372:35)
    at beginWork$1 (http://localhost:3000/static/js/0.chunk.js:78114:11)
    at performUnitOfWork (http://localhost:3000/static/js/0.chunk.js:76950:16)
    at workLoopSync (http://localhost:3000/static/js/0.chunk.js:76887:9)
    at renderRootSync (http://localhost:3000/static/js/0.chunk.js:76853:11)
    at performSyncWorkOnRoot (http://localhost:3000/static/js/0.chunk.js:76470:22)
    at http://localhost:3000/static/js/0.chunk.js:65723:30
    at unstable_runWithPriority (http://localhost:3000/static/js/0.chunk.js:109251:16)
    at runWithPriority$1 (http://localhost:3000/static/js/0.chunk.js:65669:14)
    at flushSyncCallbackQueueImpl (http://localhost:3000/static/js/0.chunk.js:65718:13)
    at flushSyncCallbackQueue (http://localhost:3000/static/js/0.chunk.js:65706:7)
    at scheduleUpdateOnFiber (http://localhost:3000/static/js/0.chunk.js:76070:13)
    at Object.enqueueSetState (http://localhost:3000/static/js/0.chunk.js:66846:9)
    at StoreBuilder.push../node_modules/react/cjs/react.development.js.Component.setState (http://localhost:3000/static/js/0.chunk.js:86153:20)
    at StoreBuilder.<anonymous> (http://localhost:3000/static/js/0.chunk.js:103139:24)
    at step (http://localhost:3000/static/js/0.chunk.js:107933:17)
    at Object.next (http://localhost:3000/static/js/0.chunk.js:107864:14)
    at fulfilled (http://localhost:3000/static/js/0.chunk.js:107819:24)
```

When I pass the url into `specUrl` it works. 

The way I am downloading the json is with the following function:
```
  async function getJson(url) {
    const resp = await fetch(url);
    const json = await resp.json();

    if (resp.status !== 200) {
      throw Error(resp.message)
    };

    return json;
  }
```

When I `console.log` the output looks correct:

![image](https://user-images.githubusercontent.com/23406594/98728567-98758200-2391-11eb-8a96-40eaefa551d2.png)

Any thoughts on this are appreciated - thanks!

**Comment by aabdaab** [comment]
I'm running into a similar issue but I get this error when I pass a json object into a `spec` prop:
<img width="710" alt="specProp" src="https://user-images.githubusercontent.com/6136899/99413664-5058e100-28f6-11eb-90e3-264b7a73f43f.png">

**Comment by pratikthanki** [comment]
Ah interesting, I think I have read/come across this. Does your swagger spec reference another spec by any chance? 

If so, you will need to consolidate them, you can use speccy (for example) to do this: https://github.com/wework/speccy

**Comment by RomanHotsiy** [comment]
@pratikthanki could you share a code snippet on how you pass the loaded spec to `RedocStandalone`?

**Comment by pratikthanki** [comment]
Yeah sure @RomanHotsiy, the `getJson` function is in another file (described above):

```js
class App extends Component {
    state = {
        data: {}
    }

    componentDidMount() {
        getJson(url)
            .then(response => {
                this.setState({
                    data: response
                });
            });
    }

    render() {
        return (
            <div className="App">
                <RedocStandalone
                    spec={response}
                    options={{
                        nativeScrollbars: true,
                        disableSearch: false,
                        hideDownloadButton: true,
                        sortPropsAlphabetically: true,
                        pathInMiddlePanel: true,
                        theme: { colors: { primary: { main: '#61affe' } } },
                    }}
                />
            </div>
        );
    }
}

export default App;
```
