### ISSUE TITLE
Error: Objects are not valid as a React child when using redoc-cli@0.9.13

### ISSUE THREAD

**Issue by sergle** [Redocly/redoc#1465]
docker run --rm -ti --name node node:14.11-slim bash

```
root@c78f7cd01704:/# yarn global add redoc-cli  
yarn global v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "redoc-cli > styled-components@5.2.1" has unmet peer dependency "react-is@>= 16.8.0".
warning "redoc-cli > redoc@2.0.0-rc.45" has unmet peer dependency "core-js@^3.1.4".
warning "redoc-cli > redoc > mobx-react@6.3.1" has incorrect peer dependency "mobx@^5.15.4 || ^4.15.4".
warning "redoc-cli > redoc > mobx-react > mobx-react-lite@2.2.2" has incorrect peer dependency "mobx@^4.0.0 || ^5.0.0".
warning "redoc-cli > redoc > swagger2openapi > better-ajv-errors@0.6.7" has unmet peer dependency "ajv@4.11.8 - 6".
[4/4] Building fresh packages...
success Installed "redoc-cli@0.9.13" with binaries:
      - redoc-cli
Done in 13.43s.

```

```
root@c78f7cd01704:/# redoc-cli bundle /tmp/openapi.yaml 
Prerendering docs
Error: Objects are not valid as a React child (found: object with keys {[object Object]}). If you meant to render a collection of children, use an array instead.
    in span
    in h1
    in Styled(styled.h1)
    in div
    in styled.div
    in div
    in styled.div
    in div
    in styled.div
    in ApiInfo
    in div
    in styled.div
    in div
    in styled.div
    in Context.Provider
    in Context.Provider
    in Context.Provider
    in Unknown
    in Redoc
    in Context.Provider
    in Context.Provider
    in ae
    at traverseAllChildrenImpl (/usr/local/share/.config/yarn/global/node_modules/react/cjs/react.development.js:1061:17)
    at traverseAllChildrenImpl (/usr/local/share/.config/yarn/global/node_modules/react/cjs/react.development.js:1023:23)
    at traverseAllChildren (/usr/local/share/.config/yarn/global/node_modules/react/cjs/react.development.js:1092:10)
    at mapIntoWithKeyPrefixInternal (/usr/local/share/.config/yarn/global/node_modules/react/cjs/react.development.js:1174:3)
    at toArray (/usr/local/share/.config/yarn/global/node_modules/react/cjs/react.development.js:1227:3)
    at ReactDOMServerRenderer.renderDOM (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.node.development.js:3954:18)
    at ReactDOMServerRenderer.render (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.node.development.js:3484:21)
    at ReactDOMServerRenderer.read (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at Object.renderToString (/usr/local/share/.config/yarn/global/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at /usr/local/share/.config/yarn/global/node_modules/redoc-cli/index.js:215:29

```

**Comment by RomanHotsiy** [comment]
Can you share the info section of your openapi definition? It looks like there is an issue in your definition.

Can you try to validate it using openapi-cli?

**Comment by sergle** [comment]
Sorry, run bundle on template instead of actual openapi spec
