### ISSUE TITLE
O.slice is not a function

### ISSUE THREAD

**Issue by blakemorgan** [Redocly/redoc#1505]
I have a valid OpenAPI document, but whenever I try to render it, I get the error: `O.slice is not a function`. 

This is the stack trace:

```
TypeError: O.slice is not a function
    at e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:29:38480)
    at Object.tokenize (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:29:38708)
    at Object.highlight (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:29:37281)
    at kt (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:96:39412)
    at t.render (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:102:52772)
    at Fa (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:72:69876)
    at Da (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:72:69671)
    at gs (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:72:105470)
    at cl (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:72:96717)
    at sl (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:72:96642)

ReDoc Version: 2.0.0-rc.48
Commit: 7b78e75
```

The stack trace in the browser dev tools is a little different:

```
TypeError: O.slice is not a function
    at e (prism.js:955)
    at Object.tokenize (prism.js:655)
    at Object.highlight (prism.js:613)
    at kt (highlight.ts:66)
    at t.render (SourceCode.tsx:16)
    at Fa (react-dom.production.min.js:182)
    at Da (react-dom.production.min.js:181)
    at gs (react-dom.production.min.js:263)
    at cl (react-dom.production.min.js:246)
    at sl (react-dom.production.min.js:246)
```

Are there any ideas what could be wrong or any suggestions for how I could continue to troubleshoot and investigate what could be causing the problem?

**Comment by adamaltman** [comment]
Are you able to provide an OpenAPI document we can use to reproduce the bug?

**Comment by blakemorgan** [comment]
Yes. The API has not been published (I'm working locally), so I've attached the spec here as a TXT file because GitHub doesn't support YML uploads. 

This is part of a monorepo with three different APIs. Two of the three APIs give that same error and one of them does render correctly, however they all render with no errors and warnings when loaded into SwaggerHub.

[example-spec.txt](https://github.com/Redocly/redoc/files/5863854/example-spec.txt)

**Comment by blakemorgan** [comment]
After cloning Redoc and running it locally, it was able to dig into the source code a bit more and identify the problem. The problem was with this response:

```yaml
description: Whether or not the bank account information is valid.
content:
  text/plain:
    schema:
      type: boolean
        example: true
```

The utils [highlight function](https://github.com/Redocly/redoc/blob/d886751261ce92dd54f1a8469230200fc1b406fe/src/utils/highlight.ts#L71) didn't know how to hightlight that. From what it looked like, PrismJS was receiving the example value `true` as a boolean and that's why `str.splice()` didn't exists. This also happened if the example value was a number.

The workaround for this was to put the example value in quotes in the OpenAPI file.

I realize this is a corner case and could be considered a poor API definition, so I have no idea if this is something you want to fix or not.

**Comment by RomanHotsiy** [comment]
Hey @blakemorgan, thanks for digging in. We'll fix it soon.
