### ISSUE TITLE
Pin styled-components version until `ReferenceError: window is not defined` fixed

### ISSUE THREAD

**Issue by pierot** [Redocly/redoc#1563]
See: https://github.com/styled-components/styled-components/issues/3444
If it's possible to pin the version number of styled-components in the mean time.

**Comment by RomanHotsiy** [comment]
@pierot I'm not sure why you see the error because redoc-cli uses a npm-shrinkwrap file which should prevent this issue.

How do you run the redoc-cli?

I just tried `npx redoc-cli@0.10.4 bundle https://redocly.github.io/redoc/openapi.yaml -o petstore.html` and it worked on my machine.

Maybe I have some cache though.

**Comment by flixx** [comment]
We've got the same error since today in our Pipelines...

```
------                                                                          
 > [apidoc 6/6] RUN redoc-cli bundle     --options.pathInMiddlePanel     -o /data/build/index.html     -t custom_template.hbs     /data/openapi/published-specs.yaml:                                                                           
#34 1.571 Prerendering docs                                                     
#34 3.167 ReferenceError: window is not defined
#34 3.167     at k (/usr/local/share/.config/yarn/global/node_modules/styled-components/dist/styled-components.cjs.js:1:7161)
#34 3.167     at e._emitSheetCSS (/usr/local/share/.config/yarn/global/node_modules/styled-components/dist/styled-components.cjs.js:1:22249)
#34 3.167     at e.getStyleTags (/usr/local/share/.config/yarn/global/node_modules/styled-components/dist/styled-components.cjs.js:1:22428)
#34 3.167     at /usr/local/share/.config/yarn/global/node_modules/redoc-cli/index.js:216:25
#34 3.167     at Generator.next (<anonymous>)
#34 3.167     at fulfilled (/usr/local/share/.config/yarn/global/node_modules/redoc-cli/index.js:6:58)
------
```

**Comment by RomanHotsiy** [comment]
How is redoc-cli installed in the pipeline? using npm or maybe yarn? Also what version do you run in pipelines?

Sorry for maybe dumb questions, I'm just trying to understand how this happens provided we have npm-shrinkwrap in place.

Thanks.

**Comment by flixx** [comment]
@RomanHotsiy No dumb question. Here you go:

```
FROM alpine:latest as apidoc
RUN apk --no-cache add git yarn && \
    yarn global add redoc-cli
COPY ./apidocs/openapi/ /data/openapi/
COPY ./apidocs/custom_template.hbs .
RUN mkdir -p /data/build

RUN redoc-cli bundle \
    --options.pathInMiddlePanel \
    -o /data/build/index.html \
    -t custom_template.hbs \
    /data/openapi/published-specs.yaml
```

**Comment by flixx** [comment]
@RomanHotsiy Indeed it does fix it! But you forgot one line.
Here for reference the working Dockerfile:

```
FROM alpine:latest as apidoc
RUN apk --no-cache add npm && \
    npm install -g redoc-cli
COPY ./apidocs/openapi/ /data/openapi/
RUN mkdir -p /data/build

RUN redoc-cli bundle \
    --options.pathInMiddlePanel \
    -o /data/build/index.html \
    /data/openapi/published-specs.yaml
```

Thanks a lot!

**Comment by RomanHotsiy** [comment]
This has been fixed in upstream: https://github.com/styled-components/styled-components/pull/3446#issuecomment-811102602
