### ISSUE TITLE
redoc-cli TypeError: rules.flatMap is not a function

### ISSUE THREAD

**Issue by etal2** [Redocly/redoc#1582]
Using the latest redoc-cli I get en error on both bundle and server commands, going back to 0.10.3 works without any issues.

`npx redoc-cli bundle ./backend.openapi.yml --output ./backend.openapi.html
TypeError: rules.flatMap is not a function
    at Object.initRules (/home/etal/.npm/_npx/1574728/lib/node_modules/redoc-cli/node_modules/@redocly/openapi-core/lib/config/rules.js:7:10)
    at /home/etal/.npm/_npx/1574728/lib/node_modules/redoc-cli/node_modules/@redocly/openapi-core/lib/bundle.js:46:39
    at Generator.next (<anonymous>)
    at /home/etal/.npm/_npx/1574728/lib/node_modules/redoc-cli/node_modules/@redocly/openapi-core/lib/bundle.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/etal/.npm/_npx/1574728/lib/node_modules/redoc-cli/node_modules/@redocly/openapi-core/lib/bundle.js:4:12)
    at bundleDocument (/home/etal/.npm/_npx/1574728/lib/node_modules/redoc-cli/node_modules/@redocly/openapi-core/lib/bundle.js:40:12)
    at /home/etal/.npm/_npx/1574728/lib/node_modules/redoc-cli/node_modules/@redocly/openapi-core/lib/bundle.js:35:16
    at Generator.next (<anonymous>)
    at fulfilled (/home/etal/.npm/_npx/1574728/lib/node_modules/redoc-cli/node_modules/@redocly/openapi-core/lib/bundle.js:5:58)`

redoc-cli 0.10.4 - 0.11.4
npm 6.14.11
node v10.23.0

**Comment by RomanHotsiy** [comment]
redoc-cli is supported only from node@12.

We'll update `engines` field in package.json in the upcoming release.

Thanks for your report!
