### ISSUE TITLE
Unable to view the developer portal.

### ISSUE THREAD

**Issue by swapna0211950** [Redocly/redoc#1587]
I have installed redoc dev portal using docker commands. Post that i have launched the url in the browser. Im seeing the below error.

Something went wrong...
Failed to fetch
Stack trace
Error: Failed to fetch
    at t.BaseResolver.<anonymous> (http://localhost:8080/redoc.standalone.js:37:13513)
    at Generator.throw (<anonymous>)
    at s (http://localhost:8080/redoc.standalone.js:37:11697)

ReDoc Version: 2.0.0-rc.53

Please help me out on what is missing.

**Comment by AlexVarchuk** [comment]
Please, contact [team@redocly.com](mailto:team@redocly.com) for our commercial product support.
