### ISSUE TITLE
Unable to resolve URL $ref under `schema`

### ISSUE THREAD

**Issue by buremba** [Redocly/redoc#1623]
If I use the following spec, redoc throws the following exception and fails to render:

```
{
   "swagger":"2.0",
   "paths":{
      "test":{
         "requestBody":{
            "description":null,
            "content":{
               "application/json":{
                  "schema":{
                     "$ref": "https://app.rakam.io/schema/report-options/segmentation.json"
                  }
               }
            }
         }
      }
   }
}
```

Exception:
```
Error: Invalid reference token: dimension
    at Function.get (webpack-internal:///./node_modules/json-pointer/index.js:54:19)
    at traverse (webpack-internal:///./node_modules/openapi-sampler/src/traverse.js:51:76)
    at traverse (webpack-internal:///./node_modules/openapi-sampler/src/traverse.js:98:12)
    at sampleArray (webpack-internal:///./node_modules/openapi-sampler/src/samplers/array.js:27:80)
    at traverse (webpack-internal:///./node_modules/openapi-sampler/src/traverse.js:118:17)
    at eval (webpack-internal:///./node_modules/openapi-sampler/src/samplers/object.js:24:73)
    at Array.forEach (<anonymous>)
    at sampleObject (webpack-internal:///./node_modules/openapi-sampler/src/samplers/object.js:18:36)
    at traverse (webpack-internal:///./node_modules/openapi-sampler/src/traverse.js:118:17)
    at allOfSample (webpack-internal:///./node_modules/openapi-sampler/src/allOf.js:16:101)
    at traverse (webpack-internal:///./node_modules/openapi-sampler/src/traverse.js:79:63)
    at Module.sample (webpack-internal:///./node_modules/openapi-sampler/src/openapi-sampler.js:24:61)
    at MediaTypeModel.generateExample (webpack-internal:///./node_modules/redoc/bundles/redoc.lib.js:9541:65)
    at new MediaTypeModel (webpack-internal:///./node_modules/redoc/bundles/redoc.lib.js:9527:18)
    at eval (webpack-internal:///./node_modules/redoc/bundles/redoc.lib.js:9585:20)
    at Array.map (<anonymous>)
    at new MediaContentModel (webpack-internal:///./node_modules/redoc/bundles/redoc.lib.js:9582:45)
    at new RequestBodyModel (webpack-internal:///./node_modules/redoc/bundles/redoc.lib.js:9631:28)
    at OperationModel.get (webpack-internal:///./node_modules/redoc/bundles/redoc.lib.js:9769:54)
    at OperationModel.get (webpack-internal:///./node_modules/redoc/bundles/redoc.lib.js:8659:42)
    at eval (webpack-internal:///./node_modules/redoc/bundles/redoc.lib.js:14191:125)
    at updateContextConsumer (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:18305:19)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:18662:14)
```

The spec is actually valid and the following modification makes it work:

```
{
   "swagger":"2.0",
   "definitions":{
      "Query":{
         "properties":{
            "test":{
               "$ref":"https://app.rakam.io/schema/report-options/segmentation.json"
            }
         }
      }
   },
   "paths":{
      "test":{
         "requestBody":{
            "description":null,
            "content":{
               "application/json":{
                  "schema":{
                     "$ref":"#/Query"
                  }
               }
            }
         }
      }
   }
}
```

I makes me think that it's a redoc issue as I just placed the remote $ref under `definitions` instead of `schema`.

**Comment by buremba** [comment]
Looks like it's not valid in OpenAPI as well. My bad.
