### ISSUE TITLE
Invalid JSON pointer exception as soon as I add produces: application/json

### ISSUE THREAD

**Issue by hilsonp** [Redocly/redoc#1624]
Using the vs-redoc-viewer extension in VSCode, I was not seeing my reply samples for my swagger 2.0 definition.
I found this bug https://github.com/Redocly/redoc/issues/1205

The problem is that as soon as I add:
```
produces:
  - application/json
```

I get the exception:
```
Something went wrong...
Invalid JSON pointer: ./CommonV1.yaml#/definitions/SelfLink
Stack trace
Error: Invalid JSON pointer: ./CommonV1.yaml#/definitions/SelfLink
    at o.parse (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:22:94936)
    at Function.e.parse (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:100:31301)
    at Function.o.get (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:22:93496)
    at Jt (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:100:55709)
    at Yt (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:100:54098)
    at Jt (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:100:55951)
    at an (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:100:58528)
    at e.generateExample (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:100:60615)
    at new e (https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:100:60032)
    at https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:100:61043

ReDoc Version: 2.0.0-rc.53
Commit: 5c8524d
```

Using swagger-ui-watcher, the responses samples (using ./CommonV1.yaml#/definitions/SelfLink) are rendered without the "produces" property hence I think my yaml file is correct.

Redoc provides a clearer view and supports the 'discriminator' in swagger 2.0 which swagger-ui does not.

Could you help me ?

Thank you.

**Comment by RomanHotsiy** [comment]
Could you please share a minimal reproducible sample?

**Comment by hilsonp** [comment]
I will as soon as possible.

**Comment by RomanHotsiy** [comment]
Closing, for now, feel free to reopen.

**Comment by vanstoker** [comment]
Hi!
I have the same problem. Can somebody had solution?
