### ISSUE TITLE
Error: "Self-referencing circular pointer"

### ISSUE THREAD

**Issue by flage-io** [Redocly/redoc#1649]
I get this error when i run:

```
$ redoc-cli bundle -o dist/docs/index.html docs/openapi.yml
Prerendering docs
Error: Self-referencing circular pointer
    at /usr/lib/node_modules/redoc-cli/node_modules/@redocly/openapi-core/lib/resolve.js:242:31
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/redoc-cli/node_modules/@redocly/openapi-core/lib/resolve.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/redoc-cli/node_modules/@redocly/openapi-core/lib/resolve.js:4:12)
    at followRef (/usr/lib/node_modules/redoc-cli/node_modules/@redocly/openapi-core/lib/resolve.js:240:24)
    at /usr/lib/node_modules/redoc-cli/node_modules/@redocly/openapi-core/lib/resolve.js:300:45
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/redoc-cli/node_modules/@redocly/openapi-core/lib/resolve.js:8:71
    at new Promise (<anonymous>)
```

Here is my file structure:
```
tree .   
.
└── docs
    ├── iap
    │   ├── paths
    │   │   ├── products.yml
    │   │   ├── product.yml
    │   │   ├── subscriptions.yml
    │   │   └── subscription.yml
    │   └── schemas
    │       ├── filter_product_type.yml
    │       ├── period_type.yml
    │       ├── period.yml
    │       ├── product_currency.yml
    │       ├── product_filters.yml
    │       ├── product_list.yml
    │       ├── product_type.yml
    │       ├── product.yml
    │       ├── subscription_params.yml
    │       ├── subscription_status.yml
    │       └── subscription.yml
    ├── openapi.yml
    └── _schemas.yml // imports all schemas from service schema folder
 ```
 
 I checked it many times, there are no circular referencing. And other tools like OpenAPI VSCode Extension by 42Crunch seems to work fine with previews.

**Comment by flage-io** [comment]
Nevermind. Seems like running `swagger-cli bundle` before `redoc-cli bundle` on that `openapi.yml` helped. 
Does `redoc-cli` support file references?

**Comment by AlexVarchuk** [comment]
@flage Yes, `redoc-cli` supports file reference.  Simple example:

```
paths:
  '/products':
    $ref: 'iap/paths/products.yaml'
```

**Comment by flage** [comment]
Well. I always get this error but swagger-cli solved this issue.
I have all of my reference form `/*/schemas/*.yml` re-referenced in `/_schemas.yml`. And `/*/paths/*.yml` referenced in `openapi.yml`.

Example:
 
 ``` yml
 # openapi.yml
paths:
  /iap:
    $ref: './iap/paths/root.yml'
components:
  schemas:
    $ref: './_schemas.yml'

 # _schemas.yml
iap.Object:
  $ref: './iap/schemas/object.yml#/iap.Object'

# iap/schemas/object.yml
iap.Object:
  type: object
  properties:
    name:
      type: string

# iap/paths/root.yml
get:
  tags:
    - iap
  responses:
    '200':
      content:
        application/json:
          schema:
            $ref: '../schemas/object.yml#/iap.Object'
 ```
 
 So existing references exist like this:
* `/openapi.yml` has a refs to `/_schemas.yml` & `/*/paths/*.yml` files. 
* `/_schemas.yml` has refs to `/*/schemas/*.yml` files.
* `/*/paths/*.yml` has refs to `/*/schemas/*.yml` files.

 There is no circular pointers here yet redoc-cli fails here. But swagger-cli works fine.

**Comment by benasher44** [comment]
I also got this with my first redocly cli project—would be great if it at least called out the cycle in the cli output

**Comment by bcheidemann** [comment]
> I also got this with my first redocly cli project—would be great if it at least called out the cycle in the cli output

+1

**Comment by kylejmcintyre** [comment]
I'm not using the CLI tools and have encountered this error when my schema has a component in it that simultaneously contains a type definition and a reference to itself: 

      ```
"GlobalWrittenLanguage": {
        "type": "string",
        "description": "The written language type",
        "$ref": "#/components/schemas/GlobalWrittenLanguage",
        "extensions": {
          "x-quiq-type-meta": {}
        },
        "exampleSetFlag": false,
        "types": [
          "string"
        ],
        "enum": [
          "af",
          "am",
          "ar"
        ]
      }
```

Getting rid of the self-ref makes it happy.

**Comment by Psychosynthesis** [comment]
Got same error

```
> tsoa spec-and-routes && openapi-typescript ./generated/swagger.json --output ./generated/types.ts

✨ openapi-typescript 7.9.1
C:\Devtools\Projects\MyProject\node_modules\@redocly\openapi-core\lib\resolve.js:264
                throw new Error('Self-referencing circular pointer');
                      ^

Error: Self-referencing circular pointer
    at followRef (C:\Devtools\Projects\MyProject\node_modules\@redocly\openapi-core\lib\resolve.js:264:23)
    at followRef (C:\Devtools\Projects\MyProject\node_modules\@redocly\openapi-core\lib\resolve.js:336:37)
    at followRef (C:\Devtools\Projects\MyProject\node_modules\@redocly\openapi-core\lib\resolve.js:336:37)
    at walk (C:\Devtools\Projects\MyProject\node_modules\@redocly\openapi-core\lib\resolve.js:239:33)
    at walk (C:\Devtools\Projects\MyProject\node_modules\@redocly\openapi-core\lib\resolve.js:236:17)
    at walk (C:\Devtools\Projects\MyProject\node_modules\@redocly\openapi-core\lib\resolve.js:236:17)
    at walk (C:\Devtools\Projects\MyProject\node_modules\@redocly\openapi-core\lib\resolve.js:236:17)
    at resolveRefsInParallel (C:\Devtools\Projects\MyProject\node_modules\@redocly\openapi-core\lib\resolve
.js:179:9)
    at resolveDocument (C:\Devtools\Projects\MyProject\node_modules\@redocly\openapi-core\lib\resolve.js:17
0:5)
    at lintDocument (C:\Devtools\Projects\MyProject\node_modules\@redocly\openapi-core\lib\lint.js:53:62)

Node.js v22.14.0

```

I tried deleting the entire node_modules folder and installing the previous version, 7.8.0. The error is the same.
