### ISSUE TITLE
the redoc can't open while swagger is good.

### ISSUE THREAD

**Issue by MRongM** [Redocly/redoc#1659]
Something went wrong...
w.slice is not a function
Stack trace
TypeError: w.slice is not a function
    at Object.matchGrammar (http://localhost:8000/static/drf-yasg/redoc/redoc.min.js:55:14920)
    at Object.tokenize (http://localhost:8000/static/drf-yasg/redoc/redoc.min.js:55:15246)
    at Object.highlight (http://localhost:8000/static/drf-yasg/redoc/redoc.min.js:55:13949)
    at bt (http://localhost:8000/static/drf-yasg/redoc/redoc.min.js:116:35757)
    at t.render (http://localhost:8000/static/drf-yasg/redoc/redoc.min.js:122:36032)
    at Ii (http://localhost:8000/static/drf-yasg/redoc/redoc.min.js:91:63011)
    at Ci (http://localhost:8000/static/drf-yasg/redoc/redoc.min.js:91:62806)
    at Ri (http://localhost:8000/static/drf-yasg/redoc/redoc.min.js:91:66640)
    at Ha (http://localhost:8000/static/drf-yasg/redoc/redoc.min.js:91:90684)
    at Va (http://localhost:8000/static/drf-yasg/redoc/redoc.min.js:91:91068)
ReDoc Version: 2.0.0-rc.14
Commit: 121bf64

**Comment by RomanHotsiy** [comment]
Can you share a snippet from your definition?

**Comment by MRongM** [comment]
The url.py is like this below:

```python
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions
from rest_framework.documentation import include_docs_urls

schema_view = get_schema_view(
   openapi.Info(
      title="titlexxx",
      default_version='v1.0',
      description="descriptionxxxx",
   ),
   public=True,
   permission_classes=(permissions.AllowAny,)
)

urlpatterns = [
    path('api/', include('app')),
    path('swagger', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]
```
The version info:
drf-yasg==1.17.1
djangorestframework==3.9.2
Django==2.2

**Comment by MRongM** [comment]
solved
