### ISSUE TITLE
Can't install dependencies to make redoc-cli 0.13.1 work

### ISSUE THREAD

**Issue by gozdal** [Redocly/redoc#1811]
**Describe the bug**
I am using `redoc-cli` (among others) to generate HTML doc from OpenAPI spec.
I have a very simply `package.json` for that:
```
{
...
  "dependencies": {
    "npm-run-all": "^4.1.4",
    "rapidoc": "^9.1.3",
    "redoc-cli": "^0.13.0",
    "swagger-cli": "^4.0.4",
    "swagger-ui-dist": "^3.52.5",
    "swagger2openapi": "^7.0.8"
  }
}
```

After `redoc-cli 0.13.1` was released I get an error like:
```
> redoc-cli bundle ....

STDERR:
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN redoc@2.0.0-rc.58 requires a peer of core-js@^3.1.4 but none is installed. You must install peer dependencies yourself.
npm WARN redoc@2.0.0-rc.58 requires a peer of mobx@^6.0.4 but none is installed. You must install peer dependencies yourself.
npm WARN redoc@2.0.0-rc.58 requires a peer of react@^16.8.4 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN redoc@2.0.0-rc.58 requires a peer of react-dom@^16.8.4 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN redoc@2.0.0-rc.58 requires a peer of styled-components@^4.1.1 || ^5.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN @redocly/react-dropdown-aria@2.0.12 requires a peer of react@^16.8.4 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @redocly/react-dropdown-aria@2.0.12 requires a peer of react-dom@^16.8.4 || ^17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @redocly/react-dropdown-aria@2.0.12 requires a peer of styled-components@^5.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN mobx-react@7.2.1 requires a peer of mobx@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN mobx-react@7.2.1 requires a peer of react@^16.8.0 || ^17 but none is installed. You must install peer dependencies yourself.
npm WARN react-tabs@3.2.3 requires a peer of react@^16.3.0 || ^17.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN mobx-react-lite@3.2.2 requires a peer of mobx@^6.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN mobx-react-lite@3.2.2 requires a peer of react@^16.8.0 || ^17 but none is installed. You must install peer dependencies yourself.

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'react'
Require stack:
- /repo/.../openapi/node_modules/redoc/bundles/redoc.lib.js
- /repo/.../openapi/node_modules/redoc-cli/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /repo/.../openapi/node_modules/redoc/bundles/redoc.lib.js:2:101489
    at /repo/.../openapi/node_modules/redoc/bundles/redoc.lib.js:2:291674
    at /repo/.../openapi/node_modules/redoc/bundles/redoc.lib.js:2:291679
    at /repo/.../openapi/node_modules/redoc/bundles/redoc.lib.js:2:81
    at Object.<anonymous> (/repo/.../openapi/node_modules/redoc/bundles/redoc.lib.js:2:191)
    at Module._compile (internal/modules/cjs/loader.js:999:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/repo/.../openapi/node_modules/redoc/bundles/redoc.lib.js',
    '/repo/.../openapi/node_modules/redoc-cli/index.js'
  ]
}
```

Following https://stackoverflow.com/questions/46053414/npm-warn-requires-a-peer-of-but-none-is-installed-you-must-install-peer#49188160 I tried to install all the missing peer dependencies with
```
npm install core-js@^3.1.4 mobx@^6.0.4 react@^16.8.4 react-dom@^16.8.4 styled-components@^4.1.1
```
This however does not fix the issue and leads to incompatibility in react:
```
> core-js@3.19.1 postinstall /node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> styled-components@4.4.1 postinstall /node_modules/styled-components
> node ./scripts/postinstall.js || exit 0

Use styled-components at work? Consider supporting our development efforts at https://opencollective.com/styled-components
npm WARN saveError ENOENT: no such file or directory, open 'package.json'
npm WARN enoent ENOENT: no such file or directory, open 'package.json'
npm WARN x No description
npm WARN x No repository field.
npm WARN x No README data
npm WARN x No license field.

+ mobx@6.3.8
+ react@16.14.0
+ react-dom@16.14.0
+ styled-components@4.4.1
+ core-js@3.19.1
added 53 packages from 61 contributors and audited 53 packages in 6.304s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (/node_modules/react/cjs/react.development.js:1465:13)
    at Object.useContext (/node_modules/react/cjs/react.development.js:1473:20)
    at $r (/node_modules/redoc/bundles/redoc.lib.js:2:183304)
    at processChild (/node_modules/redoc-cli/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/node_modules/redoc-cli/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/node_modules/redoc-cli/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/node_modules/redoc-cli/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/node_modules/redoc-cli/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at /node_modules/redoc-cli/index.js:220:29
    at Generator.next (<anonymous>)
```

**Expected behavior**
I'd expect correct dependencies to be installed with `npm i redoc-cli`

**Additional context**

`npm --version`
```
6.14.15
```
`node --version`
```
v12.22.7
```

**Comment by AlexVarchuk** [comment]
@gozdal Hi! Thanks for the issue. We have `react` in peer dependencies. Try to switch npm@7 and do a clean install.  npm7 is installing peer dependencies automatically. Thanks.

**Comment by gozdal** [comment]
Thanks, indeed npm 7 and 8 works.
