### ISSUE TITLE
Reference Error: Document is not defined

### ISSUE THREAD

**Issue by json0007** [Redocly/redoc#1872]
Ya'll broke somethin in the recent release 13.4.  I can not run any commands. Any reference to the package 'redoc-cli' returns the following error.  Even 'redoc-cl --help' fails. It is completely broken.

ReferenceError: document is not defined
    at l (C:\Users\jwilson2\AppData\Roaming\npm\node_modules\[4mredoc-cli[24m\node_modules\[4mredoc[24m\bundles\redoc.lib.js:2:24934)
    at f (C:\Users\jwilson2\AppData\Roaming\npm\node_modules\[4mredoc-cli[24m\node_modules\[4mredoc[24m\bundles\redoc.lib.js:2:26195)
    at a (C:\Users\jwilson2\AppData\Roaming\npm\node_modules\[4mredoc-cli[24m\node_modules\[4mredoc[24m\bundles\redoc.lib.js:2:24873)
    at e.exports (C:\Users\jwilson2\AppData\Roaming\npm\node_modules\[4mredoc-cli[24m\node_modules\[4mredoc[24m\bundles\redoc.lib.js:2:26597)
    at C:\Users\jwilson2\AppData\Roaming\npm\node_modules\[4mredoc-cli[24m\node_modules\[4mredoc[24m\bundles\redoc.lib.js:757:89
    at C:\Users\jwilson2\AppData\Roaming\npm\node_modules\[4mredoc-cli[24m\node_modules\[4mredoc[24m\bundles\redoc.lib.js:1739:3291
    at C:\Users\jwilson2\AppData\Roaming\npm\node_modules\[4mredoc-cli[24m\node_modules\[4mredoc[24m\bundles\redoc.lib.js:1739:3296
    at C:\Users\jwilson2\AppData\Roaming\npm\node_modules\[4mredoc-cli[24m\node_modules\[4mredoc[24m\bundles\redoc.lib.js:2:81
    at Object.<anonymous> (C:\Users\jwilson2\AppData\Roaming\npm\node_modules\[4mredoc-cli[24m\node_modules\[4mredoc[24m\bundles\redoc.lib.js:2:191)
[90m    at Module._compile (node:internal/modules/cjs/loader:1101:14)[39m

Reverting back to 13.2 and everything works fine

**Comment by TitaneBoy** [comment]
I can confirm I have the same behavior here...

**Comment by wesleividmar** [comment]
I Have the same error!

**Comment by Herrick19** [comment]
So Do I

**Comment by RomanHotsiy** [comment]
I'm on it.

**Comment by RomanHotsiy** [comment]
New release is coming in 10-15min.

**Comment by RomanHotsiy** [comment]
This is fixed in `redoc-cli@0.13.5`. I apologize for the troubles and for the fix to take so long 🙈

**Comment by Herrick19** [comment]
> This is fixed in `redoc-cli@0.13.5`. I apologize for the troubles and for the fix to take so long 🙈

Yes you better be sorry !!!

Seriously, thanks a lot for the quick fix, greatly appreciated.

**Comment by RomanHotsiy** [comment]
@Herrick19 thanks for confirmation!
