### ISSUE TITLE
Document sample script not working

### ISSUE THREAD

**Issue by msl9204** [Redocly/redoc#1995]
I tried this document `https://redocly.com/docs/redoc/deployment/cli/ `

and tried this example script
```shell
npx redoc-cli build http://petstore.swagger.io/v2/swagger.json -t custom.hbs --templateOptions.metaDescription "Page meta description"
```

### Describe the error
[ReDoc Compatibility mode]: Converting OpenAPI 2.0 to OpenAPI 3.0
Prerendering docs
TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at new URL (node:internal/url:625:22)
    at new vo (/Users/ms/.npm/_npx/088c5868f11c5564/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:41:74350)
    at new Ro (/Users/ms/.npm/_npx/088c5868f11c5564/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:41:78172)
    at new Tl (/Users/ms/.npm/_npx/088c5868f11c5564/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:1176:2881)
    at Module.<anonymous> (/Users/ms/.npm/_npx/088c5868f11c5564/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:1176:2659)
    at Generator.next (<anonymous>)
    at i (/Users/ms/.npm/_npx/088c5868f11c5564/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:1176:2413)

### Env
node : v16.13.2
npx : 8.1.2

**Comment by AlexVarchuk** [comment]
Hi! @msl9204, thank you for the bug reporting. We'll fix it soon.

**Comment by AlexVarchuk** [comment]
@msl9204 also, before we fix it you can try `redoc-cli` use prev version(0.13.11).
```
npx redoc-cli@0.13.11 buildhttp://petstore.swagger.io/v2/swagger.json -t custom.hbs --templateOptions.metaDescription "Page meta description"
```
