### ISSUE TITLE
build: Maximum call stack size exceeded since v2.0.0-rc.74

### ISSUE THREAD

**Issue by m-mohr** [Redocly/redoc#2114]
**Describe the bug**
When I run `redoc-cli build openapi.yaml -o redoc.html --title "openEO API" --cdn --options.expandResponses "200,201,202,203,204" --options.pathInMiddlePanel true`

I get an error:
```
Prerendering docs
RangeError: Maximum call stack size exceeded
    at Ln.init (C:\Dev\openeo-api\node_modules\redoc-cli\node_modules\redoc\bundles\redoc.lib.js:41:65120)
    at new Ln (C:\Dev\openeo-api\node_modules\redoc-cli\node_modules\redoc\bundles\redoc.lib.js:41:63105)
    at C:\Dev\openeo-api\node_modules\redoc-cli\node_modules\redoc\bundles\redoc.lib.js:41:66177
    at Array.map (<anonymous>)
    at Ln.initOneOf (C:\Dev\openeo-api\node_modules\redoc-cli\node_modules\redoc\bundles\redoc.lib.js:41:65954)
    at Ln.init (C:\Dev\openeo-api\node_modules\redoc-cli\node_modules\redoc\bundles\redoc.lib.js:41:64512)
    at new Ln (C:\Dev\openeo-api\node_modules\redoc-cli\node_modules\redoc\bundles\redoc.lib.js:41:63105)
    at new Wn (C:\Dev\openeo-api\node_modules\redoc-cli\node_modules\redoc\bundles\redoc.lib.js:41:71240)
    at C:\Dev\openeo-api\node_modules\redoc-cli\node_modules\redoc\bundles\redoc.lib.js:41:68582
    at Array.map (<anonymous>)
```

**Expected behavior**

Build runs flawlessly.

**Minimal reproducible OpenAPI snippet(if possible)**
Not sure what causes this, so here's the link to the OpenAPI file: https://github.com/Open-EO/openeo-api/blob/draft/openapi.yaml

**Additional context**
Seems to happen since v2.0.0-rc.74 - PR #2072 seems suspicious.

**Comment by felipeloha** [comment]
@AlexVarchuk do you think this is related https://github.com/Redocly/redocly-cli/issues/799?

**Comment by felipeloha** [comment]
@AlexVarchuk how can I know in which version this is solved?

**Comment by AlexVarchuk** [comment]
@felipeloha We'll make the next release today.

**Comment by felipeloha** [comment]
@AlexVarchuk does this fix apply for https://www.npmjs.com/package/@redocly/cli ?
sorry for the many questions

**Comment by AlexVarchuk** [comment]
should fix

**Comment by AlexVarchuk** [comment]
Hi @felipeloha, released [here](https://github.com/Redocly/redoc/commit/87c79916df816ef8e01250d8de647ce77bc66f96).
I tested your result. It works ok.
```bash
npx @redocly/cli@latest preview-docs ./sample.json
```

https://user-images.githubusercontent.com/14113673/184137718-f0b35c67-4800-41fd-bee5-c01fc9cd270c.mov

**Comment by felipeloha** [comment]
thanks
