### ISSUE TITLE
I have problem to generate HTML

### ISSUE THREAD

**Issue by Antonio-Russo** [Redocly/redoc#2146]
Thanks for any help in advance.

My error 

Something went wrong...
Cannot read properties of undefined (reading 'description')
Stack trace
TypeError: Cannot read properties of undefined (reading 'description')
    at new Tl (https://redocly.github.io/redoc/redoc-demo.bundle.js:39:101662)
    at new Uu (https://redocly.github.io/redoc/redoc-demo.bundle.js:39:136623)
    at new Jg (https://redocly.github.io/redoc/redoc-demo.bundle.js:1316:2955)
    at https://redocly.github.io/redoc/redoc-demo.bundle.js:117:1345
    at Object.Pa [as useMemo] (https://redocly.github.io/redoc/redoc-demo.bundle.js:8:442439)
    at t.useMemo (https://redocly.github.io/redoc/redoc-demo.bundle.js:8:503453)
    at Ep (https://redocly.github.io/redoc/redoc-demo.bundle.js:117:1302)
    at ia (https://redocly.github.io/redoc/redoc-demo.bundle.js:8:437735)
    at qa (https://redocly.github.io/redoc/redoc-demo.bundle.js:8:447253)
    at Bs (https://redocly.github.io/redoc/redoc-demo.bundle.js:8:490442)

ReDoc Version: 2.0.0-rc.76
Commit: acb72d5e

**Comment by AlexVarchuk** [comment]
Hi @Antonio-Russo. Please validate your definition.
You can run
```
npx @redocly/cli lint path-to-root-file.yaml
```
 If it doesn't help you, add more details, a definition sample, and steps to reproduce.
 Thanks.

**Comment by AlexVarchuk** [comment]
It seems the definition is not valid.
If you reproduce it again please feel free to reopen this isuue.
