### ISSUE TITLE
TypeError: (t.security || e.spec.security || []).map is not a function

### ISSUE THREAD

**Issue by 0x0elliot** [Redocly/redoc#2187]
**Describe the bug**
Redoc gives this stack trace: 
```
TypeError: (t.security || e.spec.security || []).map is not a function
    at new _u (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:39:82384)
    at df.getOperationsItems (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:750:5142)
    at df.getTagsItems (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:750:4782)
    at df.buildStructure (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:750:3908)
    at new Xd (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:750:1937)
    at new ey (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:1316:2955)
    at https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:117:1345
    at Object.Pa [as useMemo] (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:8:447842)
    at t.useMemo (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:8:509165)
    at Mu (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:117:1302)

ReDoc Version: 2.0.0
Commit: 5fb4daa
```

Any clue what's messing up? Hoping this serves as a primer for anyone else who encounters the same bug again in the future.

**Comment by 0x0elliot** [comment]
For anyone who stumbles across this, you can refer to this commit to see how i fixed the bug:
https://github.com/intelowlproject/IntelOwl/pull/1242/commits/dbc3f1fe45629ea8800e8a7e01084cb2d2f816e4

(pay attention to the change in `/api/get_playbook_configs` API endpoint.)

**Comment by AlexVarchuk** [comment]
Hi @0x0elliot, thank you for the issue. You had an invalid definition.
To prevent problems like this you can use a linter for it. For example [@redocly/cli](https://www.npmjs.com/package/@redocly/cli).

```
npx @redocly/cli lint path-to-root-file.yaml
```
