### ISSUE TITLE
TypeError:  t.toLowerCase is not a function

### ISSUE THREAD

**Issue by kolinkovlad** [Redocly/redoc#2244]
**Describe the bug**
While trying to generate/render API docs with the following command `npx -y 'redoc-cli@0.13' build -o apidocs/index.html apidocs/open-spec.json` getting an error:
```
Prerendering docs
TypeError: t.toLowerCase is not a function
    at i.u [as add] (/Users/vlad/.npm/_npx/91fbbb3fd21eb9c8/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:2:8081)
    at oi.add (/Users/vlad/.npm/_npx/91fbbb3fd21eb9c8/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:41:89694)
    at /Users/vlad/.npm/_npx/91fbbb3fd21eb9c8/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:41:89585
    at Array.forEach (<anonymous>)
    at t (/Users/vlad/.npm/_npx/91fbbb3fd21eb9c8/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:41:89549)
    at /Users/vlad/.npm/_npx/91fbbb3fd21eb9c8/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:41:89620
    at Array.forEach (<anonymous>)
    at t (/Users/vlad/.npm/_npx/91fbbb3fd21eb9c8/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:41:89549)
    at oi.indexItems (/Users/vlad/.npm/_npx/91fbbb3fd21eb9c8/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:41:89635)
    at new rc (/Users/vlad/.npm/_npx/91fbbb3fd21eb9c8/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:1318:3349)
```

**Expected behavior**
Successfully generated API docs

**Additional context**
redoc-cli version 0.13 (latest)
npm version: 8.19.2
node version 18.12.1

**Comment by kolinkovlad** [comment]
Not an issue. It was problem with `open-spec.json` file.
