### ISSUE TITLE
Unable to login via CLI (error: UNABLE_TO_GET_ISSUER_CERT_LOCALLY)

### ISSUE THREAD

**Issue by bookofjames** [Redocly/redoc#2276]
**Describe the bug**
When trying to login via CLI, I get an error UNABLE_TO_GET_ISSUER_CERT_LOCALLY.
Steps:
1. generate API key on redocly website
2. execute command `npx @redocly/cli login --verbose` -> prompts for my API key
3. paste API key from step 1
4. error below
```
  🔑 Copy your API key from https://app.redocly.com/profile and paste it below:

  
  Logging in...
FetchError: request to https://api.redocly.com/registry failed, reason: unable to get local issuer certificate
    at ClientRequest.<anonymous> (/Users/jamesleegovtech/dev/openapi-starter/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (events.js:400:28)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  type: 'system',
  errno: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY',
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}
(node:10499) UnhandledPromiseRejectionWarning: Error: Authorization failed. Please check if you entered a valid API key.
    at RedoclyClient.<anonymous> (/Users/jamesleegovtech/dev/openapi-starter/node_modules/@redocly/openapi-core/lib/redocly/index.js:129:23)
    at Generator.throw (<anonymous>)
    at rejected (/Users/jamesleegovtech/dev/openapi-starter/node_modules/@redocly/openapi-core/lib/redocly/index.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:10499) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:10499) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**
expected to login successfully

**Additional context**
Tried different solutions from stackoverflow but unsuccessful:

- Turning off strict ssl: npm config set strict-ssl=false
- Changing the registry to http instead of https: npm config set registry http://registry.npmjs.org/

Not sure what I should do to generate local cert?
Please help!

**Comment by AlexVarchuk** [comment]
Hi @bookofjames, thank you for the reporting issue. I am transferring the issue to the relative repository.
