### ISSUE TITLE
ReferenceError: process is not defined when running example from README

### ISSUE THREAD

**Issue by mitasov-ra** [Redocly/redoc#2323]
**Describe the bug**
I copied HTML example from the README and tried to open it, but got `ReferenceError: process is not defined` error.

```
Something went wrong...
process is not defined
Stack trace
ReferenceError: process is not defined
    at Object.resolve (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:8:301818)
    at t.BaseResolver.resolveExternalRef (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:8:76499)
    at t.BaseResolver.<anonymous> (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:8:77225)
    at Generator.next (<anonymous>)
    at https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:8:74930
    at new Promise (<anonymous>)
    at r (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:8:74675)
    at t.BaseResolver.resolveDocument (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:8:77178)
    at https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:8:33256
    at Generator.next (<anonymous>)

ReDoc Version: 2.0.0
Commit: 5fb4daa
```

HTML:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Redoc</title>
    <!-- needed for adaptive design -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">

    <!--
    Redoc doesn't change outer page styles
    -->
    <style>
        body {
            margin: 0;
            padding: 0;
        }
    </style>
</head>
<body>
<redoc spec-url='openapi.yaml'></redoc>
<script src="https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js"> </script>
</body>
</html>
```

**Comment by romanpryshliak** [comment]
Hi @mitasov-ra,

Loading local OpenAPI definitions is impossible without running a web server because of issues with [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) and other security reasons.

Please refer to this article describing how to [Run Redoc locally](https://redocly.com/docs/redoc/deployment/intro/#how-to-run-redoc-locally).

In case you use VS Code, you can also install a live server extension to preview the docs.

**Comment by scottpopplewell** [comment]
hi @romanpryshliak , to @mitasov-ra's point, the readme docs indicate you can use a local relative path file for HTML installation. Should we update that documentation?

https://github.com/Redocly/redoc#add-an-html-element-to-the-page
