### ISSUE TITLE
Qi.withComponent error using styled-components ^6.0.0-rc3

### ISSUE THREAD

**Issue by byrne-greg** [Redocly/redoc#2336]
**Describe the bug**
Using the `RedocStandalone` react component with Nextjs and the latest `styled-component`, I encounter a `Qi.withComponent` error.

Rolling back `styled-components` to v5.x fixes this issue

**Expected behavior**
No errors

**Minimal reproducible OpenAPI snippet(if possible)**
1. Follow the [instructions](https://nextjs.org/docs/getting-started/installation) to create a new Next.js app
2. Follow the [instructions](https://redocly.com/docs/redoc/deployment/intro/) to get started with Redoc
     - Install the redoc-required components
        - `yarn add redoc react react-dom mobx styled-components core-js`
4. Add the reference script to the `layout.tsx` (`<script src="https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js"> </script>`)
5. Create a page or embed the `RedocStandalone` on the page somewhere

![image](https://github.com/Redocly/redoc/assets/5464272/f6849431-5b85-4966-86c1-25fcf520e789)

**Screenshots**
![image](https://github.com/Redocly/redoc/assets/5464272/006563e7-b035-453b-8e6c-f1aedeb37653)

**Additional context**
Stacktrace
```
Uncaught TypeError: Qi.withComponent is not a function
    at eval (webpack-internal:///(app-client)/./node_modules/redoc/bundles/redoc.browser.lib.js:647:12)
    at eval (webpack-internal:///(app-client)/./node_modules/redoc/bundles/redoc.browser.lib.js:1808:3444)
    at eval (webpack-internal:///(app-client)/./node_modules/redoc/bundles/redoc.browser.lib.js:1808:3449)
    at eval (webpack-internal:///(app-client)/./node_modules/redoc/bundles/redoc.browser.lib.js:3:37)
    at eval (webpack-internal:///(app-client)/./node_modules/redoc/bundles/redoc.browser.lib.js:3:43)
    at (app-client)/./node_modules/redoc/bundles/redoc.browser.lib.js (page.js:1683:1)
    at options.factory (webpack.js:716:31)
    at __webpack_require__ (webpack.js:37:33)
    at fn (webpack.js:371:21)
    at eval (webpack-internal:///(app-client)/./app/redoc/page.tsx:8:63)
    at (app-client)/./app/redoc/page.tsx (page.js:1021:1)
    at options.factory (webpack.js:716:31)
    at __webpack_require__ (webpack.js:37:33)
    at fn (webpack.js:371:21)
    at self.__next_require__ (webpack-internal:///(app-client)/./node_modules/next/dist/client/app-index.js:52:17)
    at requireModule (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js:144:32)
    at initializeModuleChunk (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js:1205:17)
    at resolveModuleChunk (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js:1163:5)
    at eval (webpack-internal:///(app-client)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js:1590:14)
```

package.json
```json
{
  "name": "redoc-standalone-test",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@types/node": "20.3.0",
    "@types/react": "18.2.11",
    "@types/react-dom": "18.2.4",
    "core-js": "^3.31.0",
    "eslint": "8.42.0",
    "eslint-config-next": "13.4.5",
    "mobx": "^6.9.0",
    "next": "13.4.5",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "redoc": "^2.0.0",
    "styled-components": "^6",
    "typescript": "5.1.3"
  }
}
```

**Comment by AlexVarchuk** [comment]
HI @byrne-greg, thank your for the issue. Styled-component v6.0.0 now is in release candidate. I prefer to wait stable version 6.0.0, and then make changes with supporting new version.

**Comment by byrne-greg** [comment]
Thanks @AlexVarchuk. I understand waiting for the stable release. Even highlighting this issue is important because
1. The Redoc Getting Started instructions don't specify a version of styled-components and, as of now, the latest will be brought in which is currently incompatible
2. Others who encounter the issue can search the repository issues for a workaround
3. Breakages in a release candidate are a good indicator for incompatibility issues likely to be faced in the next major version

**Comment by lornajane** [comment]
Thanks @byrne-greg ! This has come up in the last week or so, there's an issue over on the CLI repo for it too, which might also be relevant for users running into the same thing https://github.com/Redocly/redocly-cli/issues/1073

**Comment by lornajane** [comment]
The dependencies were updated to address this issue, so I'm closing it - but please let us know if you're still seeing a problem with this.
