### ISSUE TITLE
Getting error while rendering RedocStandalone

### ISSUE THREAD

**Issue by sentaur-athena** [Redocly/redoc#2374]
**Describe the bug**
I installed redoc and dependencies, created a simple react component that calls RedocStandalone and tested on localhost:3000. It returns the following error:
```
Error: fs.lstatSync is not a function
    at BaseResolver.eval (webpack-internal:///./node_modules/@redocly/openapi-core/lib/resolve.js:123:23)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///./node_modules/@redocly/openapi-core/lib/resolve.js:8:71)
    at new Promise (<anonymous>)
    at __awaiter (webpack-internal:///./node_modules/@redocly/openapi-core/lib/resolve.js:4:12)
    at BaseResolver.loadExternalRef (webpack-internal:///./node_modules/@redocly/openapi-core/lib/resolve.js:106:16)
    at BaseResolver.eval (webpack-internal:///./node_modules/@redocly/openapi-core/lib/resolve.js:153:30)
    at Generator.next (<anonymous>)
    at eval (webpack-internal:///./node_modules/@redocly/openapi-core/lib/resolve.js:8:71)
    at new Promise (<anonymous>)
```

This is the code for my component:
```
import React from 'react';
import {RedocStandalone} from 'redoc';

export default function RedocComponent() {
  return (
    <div>
      <RedocStandalone specUrl="localhost:3000/open-api-new.json" />
    </div>
  );
}
```

Note that I already built the demo on redoc using the same json so the format there shouldn't be a problem. But also it's an fs issue so not related.

**Comment by sentaur-athena** [comment]
It might be related to my node.js version so closing for now.

**Comment by nalesnichok** [comment]
@ZyzychO please take a look. Thank you!

**Comment by ZyzychO** [comment]
@sentaur-athena We appreciate your patience! 

The issue happens because React app doesn't see the file **open-api-new.json** by the path: **localhost:3000/open-api-new.json"**

There are 2 possible ways to fix it. 

1. Host your API definition online. 
Example: `specUrl="http://petstore.swagger.io/v2/swagger.json"`
2. Import it as a component,  please check the screenshot attached. 

<img width="1061" alt="Screenshot 2023-08-09 at 18 56 13" src="https://github.com/Redocly/redoc/assets/106024790/89d9289b-c75f-4b58-b9e3-8572056fee4d">
<img width="1005" alt="Screenshot 2023-08-09 at 18 54 59" src="https://github.com/Redocly/redoc/assets/106024790/ada9bbb7-1aa0-4290-89a9-b89b6aa5a1da">
