### ISSUE TITLE
[2.1.0] TypeError: is(...).replace is not a function

### ISSUE THREAD

**Issue by Starfox64** [Redocly/redoc#2385]
**Describe the bug**
After the release of 2.1.0, the `Something went wrong...` error is displayed.

```
TypeError: is(...).replace is not a function
    at https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js:1202:826
    at https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js:1092:9329
    at https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js:1092:3516
    at Ke (https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js:2:534482)
    at t.track (https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js:2:538805)
    at Ch (https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js:1092:3492)
    at l (https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js:1092:9307)
    at oa (https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js:2:362151)
    at Ba (https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js:2:371669)
    at Fa (https://cdn.jsdelivr.net/npm/redoc@latest/bundles/redoc.standalone.js:2:371003)
```

Reverting to 2.0.0 solves this issue.

**Expected behavior**
No error.

**Minimal reproducible OpenAPI snippet(if possible)**
https://demo.franchiseoncloud.fr/v2/openapi

**Screenshots**
N/A

**Additional context**
N/A

**Comment by gmoorcroft** [comment]
Experiencing the same issue. 
Sample yaml file that is failing on 2.1.0 and succeeding on 2.0.0 is available here - https://www.thalesdocs.com/dpod/extern/api/swagger-public.yaml

**Comment by yilunandrewgao** [comment]
This error seems to occur when there's a `default: []` in the openapi file. Is this [code](https://github.com/Redocly/redoc/blob/main/src/components/Fields/FieldDetails.tsx#L56) trying to call `replace` on an empty list?

**Comment by RomanHotsiy** [comment]
We're looking into it

**Comment by AlexVarchuk** [comment]
Released. Please verify in 2.1.1

**Comment by adamaltman** [comment]
@AlexVarchuk please add tests to prevent regressions.
