### ISSUE TITLE
How to use this with svelte?

### ISSUE THREAD

**Issue by baseplate-admin** [Redocly/redoc#2411]
Hi,

Thanks for creating this awesome package. I was wondering how to import this into an svelte app?

```svelte
<script lang="ts">
    import { onMount } from "svelte";

    onMount(async () => {
        // @ts-ignore
        await import("redoc/bundles/redoc.standalone.js");
    });
</script>

<redoc spec-url="/openapi/schema.yaml"></redoc>
```

Currently i am following this approach but it results in :
```ts
X [ERROR] Could not resolve "null"

    node_modules/redoc/bundles/redoc.standalone.js:2:90:
      2 │ ...ction(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t(require("null")):"function"==typeof define&&define.amd?define(["null"],t):"object"==typeof exports?e...
        ╵                                                                                          ~~~~~~

  You can mark the path "null" as external to exclude it from the bundle, which will remove this
  error. You can also surround this "require" call with a try/catch block to handle this failure at
  run-time instead of bundle-time.

7:11:08 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/redoc/bundles/redoc.standalone.js:2:90: ERROR: Could not resolve "null"
    at failureErrorWithLog (C:\Programming\test\CoreProject-V3-UI\node_modules\esbuild\lib\main.js:1646:15)
    at C:\Programming\test\CoreProject-V3-UI\node_modules\esbuild\lib\main.js:1058:25
    at C:\Programming\test\CoreProject-V3-UI\node_modules\esbuild\lib\main.js:1522:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ```

**Comment by AlexVarchuk** [comment]
Hi @baseplate-admin. Thank you for the question. I am not familiar with svetle, but seems you need wrapper for using React components in Svetle. I investigated it and found [approach](https://stackoverflow.com/questions/56313219/can-i-use-react-components-in-svelte).

Code is terrible and need some improvements.

```js
<script>
  import { onMount } from "svelte";
  import React from "react";
  import { RedocStandalone } from "redoc";
  import { createRoot } from "react-dom/client";

  const e = React.createElement;
  class Documentation extends React.Component {
    render() {
      return e(RedocStandalone, {
        specUrl: "http://petstore.swagger.io/v2/swagger.json",
        options: {
          nativeScrollbars: true,
          theme: { colors: { primary: { main: "#dd5522" } } },
        },
      });
    }
  }
  /**
   * @type {HTMLDivElement}
   */
  let container;
  onMount(function () {
    createRoot(container).render(e(Documentation));
  });
</script>

<main>
  <div bind:this={container} />
</main>
```


Also, you can use Redoc standalone in HTML like that. But that approach didn't suit me.
```html
<script>
  console.log('run Redoc in svetle component')

</script>

<main>
  <script src="https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js"/>
  <redoc spec-url='http://petstore.swagger.io/v2/swagger.json'></redoc>
</main>
```


Hope it helps you.


If you have additional question about that, feel free to reopen the issue.

**Comment by mulder999** [comment]
The suggested solution is not working properly with sveltekit v2. The navigation is broken in most browsers (excepted Chrome)

**Comment by matteopolak** [comment]
> The suggested solution is not working properly with sveltekit v2. The navigation is broken in most browsers (excepted Chrome)

I made my own wrapper for it and extracted it into an npm package (`redoc-svelte`), but feel free to just copy-paste it if it works for you. It works in SvelteKit v2 (incl. navigation), some weird issues in dev mode, but works fine in prod. There's a demo running at <https://redoc-svelte.pages.dev>

`$lib/RedocStandalone.svelte`
```svelte
<script lang="ts">
  import { createRoot, type Root } from 'react-dom/client';
  import { createElement } from 'react';
  import type { RedocRawOptions } from 'redoc';

  import { createEventDispatcher, onMount } from 'svelte';

  export let spec: object | undefined = undefined;
  export let specUrl: string | undefined = undefined;
  export let options: RedocRawOptions | undefined = undefined;

  const dispatch = createEventDispatcher<{ loaded?: Error }>();

  onMount(async () => {
    redoc = await import('redoc');
    root = createRoot(container);
  });

  $: if (root && container && redoc) {
    root.render(
      createElement(redoc.RedocStandalone, {
        spec,
        specUrl,
        options,
        onLoaded: (e?: Error) => {
          dispatch('loaded', e);
        },
      }),
    );
  }

  let redoc: typeof import('redoc') | undefined = undefined;
  let root: Root | undefined = undefined;
  let container: HTMLDivElement;
</script>

<div bind:this={container} />
```

`+page.svelte`
```svelte
<script lang="ts">
  import RedocStandalone from '$lib/RedocStandalone.svelte';
</script>

<RedocStandalone
  specUrl="https://redocly.github.io/redoc/openapi.yaml"
  options={{
    nativeScrollbars: true,
    theme: {
      colors: {
        primary: { main: '#ff3e00' },
      },
    },
  }}
  on:loaded={e => console.log('loaded', e?.detail)}
/>
```

**Comment by mulder999** [comment]
Thanks for feedback, I ended up using a slightly different approach:

```typescript
<script lang="ts">
  import { browser } from "$app/environment";
  import { onMount, onDestroy } from "svelte";
  import React from "react";
  import { RedocStandalone } from "redoc";
  import { hydrateRoot, type Root } from "react-dom/client";
  import { renderToString } from "react-dom/server";

  const swaggerUrl = "/swagger/dt-v3.yaml";

  const reactComponent = React.createElement(RedocStandalone, {
    specUrl: swaggerUrl,
    options: {
      ...
    },
  });

  let container: HTMLDivElement;
  let reactRoot: Root | undefined = undefined;

  const html: string = renderToString(reactComponent);

  onMount(() => {
    if (browser) {
      reactRoot = hydrateRoot(container, reactComponent);
    }
  });

  onDestroy(() => {
    reactRoot?.unmount();
  });
</script>

<div id="redocly" bind:this={container}>{@html html}</div>
```

It works fine in every environment and with every browsers. 
In a perfect dreamland, I had expected the SSR code to incorporate more than just the "Loading..." HTML.
