### ISSUE TITLE
build-docs: Warning: Received `false` for a non-boolean attribute `deprecated`

### ISSUE THREAD

**Issue by unional** [Redocly/redoc#2420]
**Describe the bug**

```
Warning: Received `false` for a non-boolean attribute `deprecated`.

If you want to write it to the DOM, pass a string instead: deprecated="false" or deprecated={value.toString()}.

If you used to conditionally omit it with deprecated={condition && value}, pass deprecated={condition ? value : undefined} instead.
```

The error comes from `redoc.lib.js` -> `styled-components.cjs.js`

There is another one:

```
Warning: Received `true` for a non-boolean attribute `active`.

If you want to write it to the DOM, pass a string instead: active="true" or active={value.toString()}
```

**Expected behavior**
No warning

**Minimal reproducible OpenAPI snippet(if possible)**

Don't have a minimum repo yet.

This is observed in 1.2.0

**Comment by wvanderdeijl** [comment]
Not 100% sure if we run into the same problem, but I can reproduce the same error with the following file
```yaml
openapi: '3.0.0'
info:
    title: Title
    version: v1alpha
paths:
    /nvschade/werkgeverstamgegevens/v1alpha/werkgevers:unrelate:
        post:
            responses:
                '200':
                    description: Foo
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Response'
components:
    schemas:
        EmptyRecord:
            title: EmptyRecord
            type: object
            properties: {}
        EmptyRecord2:
            title: EmptyRecord2
            type: object
            properties: {}
        Response:
            title: Response
            oneOf:
                - $ref: '#/components/schemas/EmptyRecord'
                - $ref: '#/components/schemas/EmptyRecord2'
```

But I only get the error when running with `--theme.openapi.expandResponses="200,201"`:

```shell
npx redocly build-docs apps/openapi/openapi.yaml --output dist/apps/openapi/index.html --theme.openapi.expandResponses="200,201"
Prerendering docs
Warning: Received `false` for a non-boolean attribute `deprecated`.

If you want to write it to the DOM, pass a string instead: deprecated="false" or deprecated={value.toString()}.

If you used to conditionally omit it with deprecated={condition && value}, pass deprecated={condition ? value : undefined} instead.
    at button
    at I (/Users/johndoe/git/node_modules/styled-components/dist/styled-components.cjs.js:1:21998)
    at El (/Users/johndoe/git/node_modules/@redocly/cli/node_modules/redoc/bundles/redoc.lib.js:1204:988)
    at div
    at I (/Users/johndoe/git/node_modules/styled-components/dist/styled-components.cjs.js:1:21998)
    at div
    at jl (/Users/johndoe/git/node_modules/@redocly/cli/node_modules/redoc/bundles/redoc.lib.js:1204:1309)
    at Ll (/Users/johndoe/git/node_modules/@redocly/cli/node_modules/redoc/bundles/redoc.lib.js:1204:2671)
    at tp (/Users/johndoe/git/node_modules/@redocly/cli/node_modules/redoc/bundles/redoc.lib.js:1616:1379)
    at Sp (/Users/johndoe/git/node_modules/@redocly/cli/node_modules/redoc/bundles/redoc.lib.js:1647:562)
    at div
    at I (/Users/johndoe/git/node_modules/styled-components/dist/styled-components.cjs.js:1:21998)
    at div
    at observerComponent (/Users/johndoe/git/node_modules/mobx-react-lite/dist/mobxreactlite.cjs.development.js:263:12)
    at div
    at Ap (/Users/johndoe/git/node_modules/@redocly/cli/node_modules/redoc/bundles/redoc.lib.js:1653:3)
    at div
    at I (/Users/johndoe/git/node_modules/styled-components/dist/styled-components.cjs.js:1:21998)
    at div
    at I (/Users/johndoe/git/node_modules/styled-components/dist/styled-components.cjs.js:1:21998)
    at observerComponent (/Users/johndoe/git/node_modules/mobx-react-lite/dist/mobxreactlite.cjs.development.js:263:12)
    at Pu (/Users/johndoe/git/node_modules/@redocly/cli/node_modules/redoc/bundles/redoc.lib.js:1668:2933)
    at div
    at I (/Users/johndoe/git/node_modules/styled-components/dist/styled-components.cjs.js:1:21998)
    at $u (/Users/johndoe/git/node_modules/@redocly/cli/node_modules/redoc/bundles/redoc.lib.js:1668:1856)
    at ju (/Users/johndoe/git/node_modules/@redocly/cli/node_modules/redoc/bundles/redoc.lib.js:1668:1688)
    at div
    at I (/Users/johndoe/git/node_modules/styled-components/dist/styled-components.cjs.js:1:21998)
    at div
    at I (/Users/johndoe/git/node_modules/styled-components/dist/styled-components.cjs.js:1:21998)
    at exports.ThemeProvider (/Users/johndoe/git/node_modules/styled-components/dist/styled-components.cjs.js:1:26613)
    at dd (/Users/johndoe/git/node_modules/@redocly/cli/node_modules/redoc/bundles/redoc.lib.js:1819:2282)
    at Oe (/Users/johndoe/git/node_modules/styled-components/dist/styled-components.cjs.js:1:15820)
Warning: Received `true` for a non-boolean attribute `active`.

If you want to write it to the DOM, pass a string instead: active="true" or active={value.toString()}.
    at button
    at I (/Users/johndoe/git/node_modules/styled-components/dist/styled-components.cjs.js:1:21998)
    at El (/Users/johndoe/git/node_modules/@redocly/cli/node_modules/redoc/bundles/redoc.lib.js:1204:988)
    at div
    at I (/Users/johndoe/git/node_modules/styled-components/dist/styled-components.cjs.js:1:21998)
    at div
    at jl (/Users/johndoe/git/node_modules/@redocly/cli/node_modules/redoc/bundles/redoc.lib.js:1204:1309)
    at Ll (/Users/johndoe/git/node_modules/@redocly/cli/node_modules/redoc/bundles/redoc.lib.js:1204:2671)
    at tp (/Users/johndoe/git/node_modules/@redocly/cli/node_modules/redoc/bundles/redoc.lib.js:1616:1379)
    at Sp (/Users/johndoe/git/node_modules/@redocly/cli/node_modules/redoc/bundles/redoc.lib.js:1647:562)
    at div
    at I (/Users/johndoe/git/node_modules/styled-components/dist/styled-components.cjs.js:1:21998)
    at div
    at observerComponent (/Users/johndoe/git/node_modules/mobx-react-lite/dist/mobxreactlite.cjs.development.js:263:12)
    at div
    at Ap (/Users/johndoe/git/node_modules/@redocly/cli/node_modules/redoc/bundles/redoc.lib.js:1653:3)
    at div
    at I (/Users/johndoe/git/node_modules/styled-components/dist/styled-components.cjs.js:1:21998)
    at div
    at I (/Users/johndoe/git/node_modules/styled-components/dist/styled-components.cjs.js:1:21998)
    at observerComponent (/Users/johndoe/git/node_modules/mobx-react-lite/dist/mobxreactlite.cjs.development.js:263:12)
    at Pu (/Users/johndoe/git/node_modules/@redocly/cli/node_modules/redoc/bundles/redoc.lib.js:1668:2933)
    at div
    at I (/Users/johndoe/git/node_modules/styled-components/dist/styled-components.cjs.js:1:21998)
    at $u (/Users/johndoe/git/node_modules/@redocly/cli/node_modules/redoc/bundles/redoc.lib.js:1668:1856)
    at ju (/Users/johndoe/git/node_modules/@redocly/cli/node_modules/redoc/bundles/redoc.lib.js:1668:1688)
    at div
    at I (/Users/johndoe/git/node_modules/styled-components/dist/styled-components.cjs.js:1:21998)
    at div
    at I (/Users/johndoe/git/node_modules/styled-components/dist/styled-components.cjs.js:1:21998)
    at exports.ThemeProvider (/Users/johndoe/git/node_modules/styled-components/dist/styled-components.cjs.js:1:26613)
    at dd (/Users/johndoe/git/node_modules/@redocly/cli/node_modules/redoc/bundles/redoc.lib.js:1819:2282)
    at Oe (/Users/johndoe/git/node_modules/styled-components/dist/styled-components.cjs.js:1:15820)

🎉 bundled successfully in: dist/apps/openapi/index.html (38 KiB) [⏱ 1ms].
```

I am using the following versions:
```
npm ls redoc
usr@0.0.0 /Users/johndoe/git
└─┬ @redocly/cli@1.2.0
  └── redoc@2.1.2
```

**Comment by adamaltman** [comment]
Thanks for the bug report!

**Comment by AlexVarchuk** [comment]
Hi, @unional @wvanderdeijl. It resolved in https://github.com/Redocly/redoc/pull/2416. We made a new release. Please verify it.

**Comment by unional** [comment]
Thanks. It is working.

**Comment by wvanderdeijl** [comment]
Works in our case as well. Thanks for fixing
