### ISSUE TITLE
Use a local file for spec-url

### ISSUE THREAD

**Issue by ma-ble** [Redocly/redoc#2489]
I want to know if it is possible to use a local file for spec-url. In the documentation this scenario is managed as a valid use case. 

[Set spec-url to a relative path if the file is local, e.g. spec-url=my-api.yaml. ](https://redocly.com/docs/redoc/deployment/html/)

For testing I download the [swagger.json](http://petstore.swagger.io/v2/swagger.json) from the example and store it in the same folder as the html file. 

`<body>
   <redoc spec-url='swagger.json'></redoc>
   <script src="https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js"> </script>
 </body>`

My error message loading the file into my browser is. 

`
Something went wrong...
process is not defined
Stack trace
ReferenceError: process is not defined
    at Object.resolve (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:2:220797)
    at t.BaseResolver.resolveExternalRef (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:2:30606)
    at t.BaseResolver.<anonymous> (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:2:31505)
    at Generator.next (<anonymous>)
    at https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:2:29037
    at new Promise (<anonymous>)
    at r (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:2:28782)
    at t.BaseResolver.resolveDocument (https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:2:31458)
    at https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js:2:5170
    at Generator.next (<anonymous>)

ReDoc Version: 2.1.3
Commit: b2d8e0f
`

I have also found an issue where using local files was not supported due to security issues: 
https://github.com/Redocly/redoc/issues/149

**Comment by lornajane** [comment]
@ma-ble Thanks for reaching out to us. You can use a local file, but you need to be serving it locally so that it is available on a localhost URL. It can be a relative URL if you're also serving the HTML page locally as well. You are correct that the advice in #149 will apply here.

I think this answers question, but feel free to let us know if you need anything else!

**Comment by varkhan** [comment]
This is still not fixed, and makes redoc unusable for my use case.

> You can use a local file, but you need to be serving it locally so that it is available on a localhost URL. It can be a relative URL if you're also serving the HTML page locally as well. 

The doc is specific:
> Set spec-url to a relative path if the file is local, e.g. spec-url=my-api.yaml. Use a full URL like the example above if it's hosted elsewhere.

"serving it locally" is not the same as "use a relative path" (and the example confirms this later interpretation)
One looks like: "http://localhost/..../spec-file.yaml"
The other looks like: "./spec-file.yaml"

Either the doc is incorrect, and needs to be fixed, or the code is incorrect, and needs to be fixed.
