### ISSUE TITLE
References from SwaggerHub

### ISSUE THREAD

**Issue by ebcFlagman** [Redocly/redoc#2636]
**Describe the problem to be solved**
We have our OpenAPI definitions in SwaggerHub and used this Plugin within IntelliJ to edit the specifications in our Git repository. But we have the problem in IntelliJ that references to other specifications on SwaggerHub cannot be resolved.

**Describe the solution you'd like**
References points to SwaggerHub should be resolved OR 

**Additional context**
`Invalid JSON pointer: https://api.swaggerhub.com/apis/patrick.wachsmuth/Reference-Demo-Common/1.0.0#/components/schemas/ApiResponse`

```
Error: Invalid JSON pointer: https://api.swaggerhub.com/apis/patrick.wachsmuth/Reference-Demo-Common/1.0.0#/components/schemas/ApiResponse
    at u.parse (http://localhost:63342/__ij-openapi-plugin/libraryResource?previewType=redoc&resourcePath=redoc.js:2635:4988)
    at Function.parse (http://localhost:63342/__ij-openapi-plugin/libraryResource?previewType=redoc&resourcePath=redoc.js:2586:23146)
    at u.get (http://localhost:63342/__ij-openapi-plugin/libraryResource?previewType=redoc&resourcePath=redoc.js:2635:3493)
    at R (http://localhost:63342/__ij-openapi-plugin/libraryResource?previewType=redoc&resourcePath=redoc.js:2702:4191)
    at Object.$e (http://localhost:63342/__ij-openapi-plugin/libraryResource?previewType=redoc&resourcePath=redoc.js:2702:9315)
    at k.generateExample (http://localhost:63342/__ij-openapi-plugin/libraryResource?previewType=redoc&resourcePath=redoc.js:2586:7329)
    at new k (http://localhost:63342/__ij-openapi-plugin/libraryResource?previewType=redoc&resourcePath=redoc.js:2586:6718)
    at http://localhost:63342/__ij-openapi-plugin/libraryResource?previewType=redoc&resourcePath=redoc.js:2586:8044
    at Array.map (<anonymous>)
    at new Ct (http://localhost:63342/__ij-openapi-plugin/libraryResource?previewType=redoc&resourcePath=redoc.js:2586:8012)
```

[Reference-Demo-1.0.0-swagger.yaml.zip](https://github.com/user-attachments/files/18280746/Reference-Demo-1.0.0-swagger.yaml.zip)

**Comment by AlexVarchuk** [comment]
Hi @ebcFlagman thank you for the issue. I  opened `https://api.swaggerhub.com/domains/<org>/<schema>/1.0.3#/components/schemas/documentId` and it gets me 404 error. Your link may not be correct and you should change it. Or, I am not sure what case you faced. Can you add more details? The minimal reproducible OpenAPI description will help a lot.

**Comment by ebcFlagman** [comment]
> Hi [@ebcFlagman](https://github.com/ebcFlagman) thank you for the issue. I opened `https://api.swaggerhub.com/domains/<org>/<schema>/1.0.3#/components/schemas/documentId` and it gets me 404 error. Your link may not be correct and you should change it. Or, I am not sure what case you faced. Can you add more details? The minimal reproducible OpenAPI description will help a lot.

Hi @AlexVarchuk I've updated the description with a public example and added the example yaml file

**Comment by AlexVarchuk** [comment]
hi @ebcFlagman. I didn't get an error what you show. 
<img width="710" alt="Image" src="https://github.com/user-attachments/assets/e6b89b49-6d17-496b-a860-006942a5a87f" />

Could you give me reproducible example of that?

**Comment by ebcFlagman** [comment]
Interessting, It seems to be a problem with the plugin itseld and not with redoc. i will open a bug at Jetbrains
