### ISSUE TITLE
Cannot read property '$ref' of undefined when using components.requestBodies

### ISSUE THREAD

**Issue by raytangRT** [Redocly/redoc#454]
I am using redoc-cli (version 0.3.5) with --watch for development and seeing Cannot read property '$ref' of undefined

Sample yaml
```
.yaml
/account/info:
    post:
...
      requestBody:
        $ref: '#/components/requestBodies/AccountNoRequestBody'
...
components:
  requestBodies:
    AccountNoRequestBody:
      description: Account No Request Body
      content:
        application/json:
          schema:
            type: object
            properties:
              accountNo:
                type: string
                example: ACC00001
                description: The Requested Account No

```

```
Something went wrong...
Cannot read property '$ref' of undefined
Stack trace
TypeError: Cannot read property '$ref' of undefined
    at e (http://localhost:13135/redoc.standalone.js:92:22719)
    at Object.n.sample (http://localhost:13135/redoc.standalone.js:92:18264)
    at e.generateExample (http://localhost:13135/redoc.standalone.js:104:95215)
    at new e (http://localhost:13135/redoc.standalone.js:104:94857)
    at http://localhost:13135/redoc.standalone.js:104:95815
    at Array.map (<anonymous>)
    at new e (http://localhost:13135/redoc.standalone.js:104:95764)
    at new <anonymous> (http://localhost:13135/redoc.standalone.js:104:96489)
    at new e (http://localhost:13135/redoc.standalone.js:104:98456)
    at Function.e.getOperationsItems (http://localhost:13135/redoc.standalone.js:104:101268)

ReDoc Version: 2.0.0-alpha.17 
Commit: de177a0
```

**Comment by raytangRT** [comment]
I can move it back to requestBody, but moving it to requestBodies makes it better

**Comment by lornajane** [comment]
Closing this since `redoc-cli` is deprecated, and I think this old issue should be fixed in the new tool. Users should [migrate to Redocly CLI](https://redocly.com/docs/cli/guides/migrate-from-redoc-cli/) - let us know if this still seems like there's something wrong?
