### ISSUE TITLE
redoc-cli doesn't work with untrustedSpec=true: TypeError: external_dompurify_.sanitize is not a function

### ISSUE THREAD

**Issue by theomega** [Redocly/redoc#831]
I'm trying to render a OpenAPI3 spec using `redoc-cli` and while this works without the options, I'm running into an issue if I provide the `--options.untrustedSpec=true`:

```
redoc-cli bundle --options.untrustedSpec=true output-openapi-merged/dev/index.yaml 
Prerendering docs
TypeError: external_dompurify_.sanitize is not a function
    at sanitize (/Users/dominik/Develop/api-collection/node_modules/redoc/bundles/redoc.lib.js:7518:103)
    at Object.children (/Users/dominik/Develop/api-collection/node_modules/redoc/bundles/redoc.lib.js:7522:21)
    at ReactDOMServerRenderer.render (/Users/dominik/Develop/api-collection/node_modules/react-dom/cjs/react-dom-server.node.development.js:3395:55)
    at ReactDOMServerRenderer.read (/Users/dominik/Develop/api-collection/node_modules/react-dom/cjs/react-dom-server.node.development.js:3144:29)
    at Object.renderToString (/Users/dominik/Develop/api-collection/node_modules/react-dom/cjs/react-dom-server.node.development.js:3629:27)
    at /Users/dominik/Develop/api-collection/node_modules/redoc-cli/index.js:184:29
    at Generator.next (<anonymous>)
    at fulfilled (/Users/dominik/Develop/api-collection/node_modules/redoc-cli/index.js:5:58)
    at <anonymous>
```
My versions are:
```
    "redoc": "^2.0.0-rc.2",
    "redoc-cli": "^0.7.0"
```

**Comment by bu4ak** [comment]
same issue

`"redoc-cli": "^0.10.4",`

**Comment by lornajane** [comment]
Closing this since `redoc-cli` is deprecated. Users should [migrate to Redocly CLI](https://redocly.com/docs/cli/guides/migrate-from-redoc-cli/) - please let us know if you see the same issue there?
