### ISSUE TITLE
bitbucket piplines failed: TypeError [ERR_INVALID_URL]: Invalid URL: /v1

### ISSUE THREAD

**Issue by xuleijian** [Redocly/redoc#911]
I got the error when run the bitbucket piplines. But 7 hours ago ,it's successful
 
redoc-cli bundle -o swagger.html swagger.yaml

+ redoc-cli bundle -o swagger.html swagger.yaml
[ReDoc Compatibility mode]: Converting OpenAPI 2.0 to OpenAPI 3.0
Prerendering docs
TypeError [ERR_INVALID_URL]: Invalid URL: /v1
    at onParseError (internal/url.js:241:17)
    at new URL (internal/url.js:319:5)
    at parseURL (/usr/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:6950:16)
    at removeQueryString (/usr/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:6940:15)
    at /usr/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:11064:137
    at Array.map (<anonymous>)
    at Object.children (/usr/lib/node_modules/redoc-cli/node_modules/redoc/bundles/redoc.lib.js:11060:104)
    at ReactDOMServerRenderer.render (/usr/lib/node_modules/redoc-cli/node_modules/react-dom/cjs/react-dom-server.node.development.js:3412:55)
    at ReactDOMServerRenderer.read (/usr/lib/node_modules/redoc-cli/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at Object.renderToString (/usr/lib/node_modules/redoc-cli/node_modules/react-dom/cjs/react-dom-server.node.development.js:3646:27)

**Comment by RomanGotsiy** [comment]
Duplicated of #910
