### ISSUE TITLE
redocly.github.io/redoc broken (403)

### ISSUE THREAD

**Issue by BenjaminPelletier** [Redocly/redoc#935]
When trying to [display any spec](https://redocly.github.io/redoc/?url=https://api.apis.guru/v2/specs/instagram.com/1.0.0/swagger.yaml):

```
Error: Error downloading https://cors.apis.guru/https://api.apis.guru/v2/specs/instagram.com/1.0.0/swagger.yaml 
HTTP ERROR 403
    at https://redocly.github.io/redoc/redoc-demo.bundle.js:52:1500
    at https://redocly.github.io/redoc/redoc-demo.bundle.js:25:133061

Error: HTTP ERROR 403
    at https://redocly.github.io/redoc/redoc-demo.bundle.js:52:1500
    at https://redocly.github.io/redoc/redoc-demo.bundle.js:25:132641

ReDoc Version: 2.0.0-rc.8-1 
Commit: 4d8cba1
```

**Comment by RomanHotsiy** [comment]
Fixed, thanks!
